"""Shot sub-stage tests (Phase 2 task 3) — PRD REQ-012, decisions.md D-18.

The behaviours proved here are the ones that lose footage or corrupt downstream
sub-stages when they break:

* shots TILE the asset — a gap is footage no Moment can ever reference again;
* `keyframeTicks` is strictly inside its own shot — OCR reading the next shot's
  first frame would attribute its text to the wrong shot;
* a static take still produces shots — zero shots starves OCR, one asset-long
  shot compresses the whole clip into a single keyframe;
* ticks come from the container timebase, never an averaged fps — `ugly.mp4` is
  genuinely VFR and an fps guess places every boundary wrong;
* every threshold reaches the index — REQ-012 says recorded, so it is asserted.

Fixture provenance is `cutdown/skills/index/fixtures/shots/README.md`; the three
transition clips were generated by ffmpeg because none of the ingest golden-set
media contains a detectable cut, fade or camera move (verified: all three
detectors return an empty list on `clean.mp4`, `ugly.mp4` and `broll-silent.mp4`).
"""

from __future__ import annotations

import functools
import json
from fractions import Fraction
from pathlib import Path

import pytest

from harness import SubStageContext, SubStageError, canonical_json
from shots import (
    DEFAULT_SHOT_CONFIG,
    Boundary,
    Timebase,
    VideoProbe,
    _keyframe_ticks,
    _time_sliced_shots,
    assert_tiles,
    build_shots,
    compute_shots,
    merge_boundaries,
    probe_video,
    rescale_ticks,
    run_shots_sub_stage,
    seconds_to_ticks,
    shot_engine_record,
)

CUTDOWN_ROOT = Path(__file__).resolve().parents[3]
INGEST = CUTDOWN_ROOT / "data" / "golden-sets" / "ingest"
FIXTURES = CUTDOWN_ROOT / "skills" / "index" / "fixtures" / "shots"

HARD_CUT_MP4 = FIXTURES / "hard-cut.mp4"
FADE_MP4 = FIXTURES / "fade.mp4"
CAMERA_CHANGE_MP4 = FIXTURES / "camera-change.mp4"
CLEAN_MP4 = INGEST / "clean.mp4"
UGLY_MP4 = INGEST / "ugly.mp4"
BROLL_MP4 = INGEST / "broll-silent.mp4"

#: 1/15360 is the mp4 container timebase every fixture in this repo carries.
VIDEO_TIMEBASE = Timebase(num=1, den=15360)

ENGINE_STUB = {"name": "test", "version": "0", "parameters": []}


@functools.lru_cache(maxsize=None)
def _detected(media_path: Path) -> str:
    """Detection is deterministic, so each fixture is decoded once per session.

    Cached as canonical JSON rather than as the dict, so a test that mutates its
    copy cannot corrupt another test's fixture. `TestDetectionOnRealMedia`'s
    determinism case deliberately bypasses this and decodes twice for real.
    """
    return canonical_json(compute_shots(media_path))


def shots_for(media_path: Path) -> list[dict]:
    return json.loads(_detected(media_path))["shots"]



def probe(duration_ticks: int = 61440) -> VideoProbe:
    return VideoProbe(timebase=VIDEO_TIMEBASE, duration_ticks=duration_ticks, avg_frame_rate=Fraction(30))


@pytest.fixture
def ctx(tmp_path: Path) -> SubStageContext:
    return SubStageContext(
        job_id="shots-1",
        asset_id="01HQZX3F5G7K9M2N4P6R8S0T2V",
        job_root=tmp_path / "jobs" / "shots-1",
        content_hash="c" * 64,
    )


class TestTickArithmetic:
    """Contract §3: integer ticks in a stated timebase, never float seconds."""

    def test_seconds_convert_exactly_at_the_engine_boundary(self) -> None:
        assert seconds_to_ticks(1.5, VIDEO_TIMEBASE) == 23040
        assert seconds_to_ticks(0.0, VIDEO_TIMEBASE) == 0

    def test_rescale_between_timebases_is_exact(self) -> None:
        # The opencv backend reports microseconds whatever the container says, so
        # a rescale that went via float seconds would drift on long assets.
        assert rescale_ticks(1_000_000, Fraction(1, 1_000_000), VIDEO_TIMEBASE) == 15360
        assert rescale_ticks(1024, Fraction(1, 15360), VIDEO_TIMEBASE) == 1024

    def test_rescale_uses_the_raw_timebase_not_a_reduced_fraction(self) -> None:
        # {num: 1001, den: 30000} is NTSC 29.97. Reducing the target through
        # `Fraction` and reading its denominator would silently change the tick
        # scale for any timebase whose num/den share a factor.
        ntsc = Timebase(num=1001, den=30000)
        assert rescale_ticks(30000, Fraction(1, 30000), ntsc) == 30
        assert rescale_ticks(2002, Fraction(1, 30000), ntsc) == 2

    def test_keyframe_is_strictly_inside_its_shot(self) -> None:
        assert _keyframe_ticks(0, 100) == 50
        # The degenerate one-tick shot: the midpoint must not land on `end`,
        # which belongs to the NEXT shot under half-open ranges.
        assert _keyframe_ticks(10, 11) == 10


class TestBoundaryMerging:
    """Three detectors, one transition — precedence decides what it is called."""

    def test_a_fade_beats_a_hard_cut_at_the_same_instant(self) -> None:
        merged = merge_boundaries(
            [Boundary(1000, "hard_cut", 0.9), Boundary(1010, "fade", 0.8)],
            merge_ticks=100,
        )
        assert [b.kind for b in merged] == ["fade"]

    def test_a_hard_cut_beats_a_camera_change_at_the_same_instant(self) -> None:
        # The low-threshold pass sees everything the high-threshold pass sees, so
        # without precedence every hard cut would also be reported as a camera
        # change and the enum would carry no information.
        merged = merge_boundaries(
            [Boundary(1000, "camera_change", 0.6), Boundary(1000, "hard_cut", 0.9)],
            merge_ticks=100,
        )
        assert [b.kind for b in merged] == ["hard_cut"]

    def test_distant_boundaries_are_not_merged(self) -> None:
        merged = merge_boundaries(
            [Boundary(1000, "hard_cut", 0.9), Boundary(5000, "fade", 0.8)],
            merge_ticks=100,
        )
        assert [(b.ticks, b.kind) for b in merged] == [(1000, "hard_cut"), (5000, "fade")]

    def test_no_candidates_yields_no_boundaries(self) -> None:
        assert merge_boundaries([], merge_ticks=100) == []


class TestTiling:
    """A gap silently loses footage — the single most expensive bug in this file."""

    def test_shots_tile_the_asset_with_no_gaps_or_overlaps(self) -> None:
        shots = build_shots(
            [Boundary(20000, "hard_cut", 0.9), Boundary(40000, "fade", 0.8)],
            probe(61440),
            DEFAULT_SHOT_CONFIG,
            ENGINE_STUB,
        )
        assert [(s["startTicks"], s["endTicks"]) for s in shots] == [
            (0, 20000),
            (20000, 40000),
            (40000, 61440),
        ]
        assert_tiles(shots, 61440)

    def test_transitions_are_carried_on_both_sides_of_a_boundary(self) -> None:
        shots = build_shots([Boundary(20000, "fade", 0.8)], probe(61440), DEFAULT_SHOT_CONFIG, ENGINE_STUB)
        assert shots[0]["transitionOut"] == "fade"
        assert shots[1]["transitionIn"] == "fade"
        # The asset head and tail are not detections and must not be labelled as
        # though something was detected there.
        assert shots[0]["transitionIn"] == "unknown"
        assert shots[-1]["transitionOut"] == "unknown"

    def test_a_gap_is_rejected(self) -> None:
        shots = build_shots([Boundary(20000, "hard_cut", 0.9)], probe(61440), DEFAULT_SHOT_CONFIG, ENGINE_STUB)
        shots[1]["startTicks"] = 21000  # one gap, 1000 ticks of lost footage
        with pytest.raises(SubStageError) as raised:
            assert_tiles(shots, 61440)
        assert raised.value.code == "SHOT_TILING_BROKEN"

    def test_shots_that_stop_short_of_the_duration_are_rejected(self) -> None:
        shots = build_shots([Boundary(20000, "hard_cut", 0.9)], probe(61440), DEFAULT_SHOT_CONFIG, ENGINE_STUB)
        shots[-1]["endTicks"] = 60000
        with pytest.raises(SubStageError) as raised:
            assert_tiles(shots, 61440)
        assert raised.value.code == "SHOT_TILING_BROKEN"

    def test_a_keyframe_outside_its_shot_is_rejected(self) -> None:
        shots = build_shots([], probe(61440), DEFAULT_SHOT_CONFIG, ENGINE_STUB)
        shots[0]["keyframeTicks"] = shots[0]["endTicks"]
        with pytest.raises(SubStageError) as raised:
            assert_tiles(shots, 61440)
        assert raised.value.code == "SHOT_KEYFRAME_OUT_OF_RANGE"

    def test_a_boundary_too_close_to_the_head_is_dropped(self) -> None:
        # 0.25 s at 1/15360 is 3840 ticks; a boundary at 100 would carve a shot
        # nobody can cut to and whose keyframe is meaningless.
        shots = build_shots([Boundary(100, "hard_cut", 0.9)], probe(61440), DEFAULT_SHOT_CONFIG, ENGINE_STUB)
        assert all(s["endTicks"] - s["startTicks"] >= 3840 for s in shots)
        assert_tiles(shots, 61440)

    def test_shot_ids_are_deterministic_and_ordinal(self) -> None:
        shots = build_shots(
            [Boundary(20000, "hard_cut", 0.9), Boundary(40000, "hard_cut", 0.9)],
            probe(61440),
            DEFAULT_SHOT_CONFIG,
            ENGINE_STUB,
        )
        assert [s["shotId"] for s in shots] == ["shot-0001", "shot-0002", "shot-0003"]


class TestStaticTakeFallback:
    """A locked-off camera must still yield usable shots (phase plan)."""

    def test_no_boundaries_yields_time_slices_not_one_asset_long_shot(self) -> None:
        shots = build_shots([], probe(61440), DEFAULT_SHOT_CONFIG, ENGINE_STUB)
        assert len(shots) > 1, "one shot spanning the asset gives OCR a single keyframe for the whole clip"
        assert shots[0]["startTicks"] == 0
        assert shots[-1]["endTicks"] == 61440
        assert_tiles(shots, 61440)

    def test_time_slices_claim_no_transition_they_did_not_detect(self) -> None:
        shots = _time_sliced_shots(probe(61440), DEFAULT_SHOT_CONFIG, ENGINE_STUB)
        assert all(s["transitionIn"] == "unknown" and s["transitionOut"] == "unknown" for s in shots)
        assert all(s["confidence"] == DEFAULT_SHOT_CONFIG["confidence_time_slice"] for s in shots)

    def test_an_asset_shorter_than_one_slice_is_a_single_shot(self) -> None:
        # Honest boundary of the rule: a 1 s clip cannot be sliced into 2 s
        # slices, and inventing sub-slices would be arbitrary.
        shots = _time_sliced_shots(probe(15360), DEFAULT_SHOT_CONFIG, ENGINE_STUB)
        assert len(shots) == 1
        assert_tiles(shots, 15360)

    def test_slicing_is_deterministic(self) -> None:
        first = _time_sliced_shots(probe(58368), DEFAULT_SHOT_CONFIG, ENGINE_STUB)
        second = _time_sliced_shots(probe(58368), DEFAULT_SHOT_CONFIG, ENGINE_STUB)
        assert canonical_json(first) == canonical_json(second)


class TestEngineRecord:
    """REQ-012: 'every threshold is recorded with the index'."""

    def test_every_configured_threshold_reaches_the_record(self) -> None:
        record = shot_engine_record(DEFAULT_SHOT_CONFIG)
        keys = {pair["key"] for pair in record["parameters"]}
        assert keys == set(DEFAULT_SHOT_CONFIG)
        for required in ("hard_cut_threshold", "fade_threshold", "camera_change_threshold", "rules_version"):
            assert required in keys

    def test_parameters_are_key_value_pairs_of_strings(self) -> None:
        # The schema's EngineParameter is closed with string values; a raw float
        # here would fail contract validation at assembly time.
        record = shot_engine_record(DEFAULT_SHOT_CONFIG)
        for pair in record["parameters"]:
            assert set(pair) == {"key", "value"}
            assert isinstance(pair["value"], str)

    def test_parameters_are_sorted_so_the_artefact_is_byte_stable(self) -> None:
        record = shot_engine_record(DEFAULT_SHOT_CONFIG)
        keys = [pair["key"] for pair in record["parameters"]]
        assert keys == sorted(keys)

    def test_the_record_names_the_installed_engine_version(self) -> None:
        import scenedetect

        record = shot_engine_record(DEFAULT_SHOT_CONFIG)
        assert record["name"] == "pyscenedetect"
        assert record["version"] == str(scenedetect.__version__)


class TestProbe:
    def test_the_container_timebase_and_exact_duration_are_read(self) -> None:
        result = probe_video(CLEAN_MP4)
        assert result.timebase == VIDEO_TIMEBASE
        # 76800 / 15360 == 5.000 s exactly, matching ffprobe's reported duration.
        assert result.duration_ticks == 76800

    def test_a_non_media_file_fails_structurally_not_with_a_traceback(self, tmp_path: Path) -> None:
        junk = tmp_path / "not-a-video.mp4"
        junk.write_bytes(b"this is not an mp4")
        with pytest.raises(SubStageError) as raised:
            probe_video(junk)
        assert raised.value.code in {"FFPROBE_FAILED", "NO_VIDEO_STREAM", "TIMEBASE_UNAVAILABLE"}


class TestDetectionOnRealMedia:
    """Positive fixture per transition kind, each with the others as controls."""

    def test_hard_cuts_are_detected_and_labelled(self) -> None:
        shots = shots_for(HARD_CUT_MP4)
        assert len(shots) == 3, "three solid-colour segments, two cuts"
        assert shots[0]["transitionOut"] == "hard_cut"
        assert shots[1]["transitionIn"] == "hard_cut"

    def test_the_hard_cut_fixture_reports_no_fade(self) -> None:
        # Negative control: the clip never goes to black, so a `fade` here would
        # mean ThresholdDetector is firing on content rather than luma.
        shots = shots_for(HARD_CUT_MP4)
        transitions = {s["transitionIn"] for s in shots} | {s["transitionOut"] for s in shots}
        assert "fade" not in transitions

    def test_a_fade_to_black_is_labelled_fade_not_hard_cut(self) -> None:
        shots = shots_for(FADE_MP4)
        transitions = {s["transitionIn"] for s in shots} | {s["transitionOut"] for s in shots}
        assert "fade" in transitions
        assert "hard_cut" not in transitions, "precedence must keep a fade from reading as a cut"

    def test_a_camera_move_is_labelled_camera_change_not_hard_cut(self) -> None:
        shots = shots_for(CAMERA_CHANGE_MP4)
        transitions = {s["transitionIn"] for s in shots} | {s["transitionOut"] for s in shots}
        assert "camera_change" in transitions
        assert "hard_cut" not in transitions, "a continuous pan is not a cut"

    def test_a_static_take_falls_back_to_time_slices(self) -> None:
        # broll-silent.mp4 is one frozen frame: every detector correctly returns
        # nothing, and the fallback is the only thing standing between OCR and
        # an empty input.
        shots = shots_for(BROLL_MP4)
        assert len(shots) >= 2
        assert all(s["transitionIn"] == "unknown" and s["transitionOut"] == "unknown" for s in shots)
        assert_tiles(shots, 61440)

    def test_every_fixture_tiles_its_asset(self) -> None:
        for media in (HARD_CUT_MP4, FADE_MP4, CAMERA_CHANGE_MP4, CLEAN_MP4, UGLY_MP4, BROLL_MP4):
            assert_tiles(shots_for(media), probe_video(media).duration_ticks)

    def test_detection_is_byte_identical_across_runs(self) -> None:
        # Contract §5. PySceneDetect is deterministic given the same decode, so a
        # difference here would mean we introduced the non-determinism.
        assert canonical_json(compute_shots(FADE_MP4)) == canonical_json(compute_shots(FADE_MP4))


class TestVariableFrameRate:
    """`ugly.mp4` is genuinely VFR: average 400/19 fps, container timebase 1/15360."""

    def test_the_average_frame_rate_really_does_disagree_with_the_timebase(self) -> None:
        # Guards the premise of every other test in this class: if this fixture
        # were secretly CFR, the VFR assertions below would pass vacuously.
        result = probe_video(UGLY_MP4)
        assert result.avg_frame_rate == Fraction(400, 19)
        assert result.avg_frame_rate != Fraction(result.timebase.den, result.timebase.num)

    def test_ticks_are_in_the_container_timebase_not_the_average_frame_rate(self) -> None:
        shots = compute_shots(UGLY_MP4)["shots"]
        assert all(s["timebase"] == {"num": 1, "den": 15360} for s in shots)
        # 19/400 would be the timebase if we had assumed the average frame rate
        # was the real one — the exact mistake this asserts against.
        assert all(s["timebase"] != {"num": 19, "den": 400} for s in shots)

    def test_the_last_shot_ends_on_the_exact_asset_duration(self) -> None:
        shots = compute_shots(UGLY_MP4)["shots"]
        # 58368 / 15360 == 3.8 s exactly. Reconstructing the duration from
        # frame count / average fps gives 80 / (400/19) = 3.8 by luck here, but
        # any boundary in between would land on the wrong frame.
        assert shots[-1]["endTicks"] == 58368
        assert shots[0]["startTicks"] == 0


class TestShotsSubStage:
    """Sub-stage wiring: resumable, and keyed on the thresholds that shaped it."""

    def test_the_second_run_is_a_cache_hit(self, ctx: SubStageContext) -> None:
        first = run_shots_sub_stage(ctx, FADE_MP4)
        assert first.cache_hit is False
        assert run_shots_sub_stage(ctx, FADE_MP4).cache_hit is True

    def test_changing_a_threshold_invalidates_the_checkpoint(self, ctx: SubStageContext) -> None:
        # REQ-005: the thresholds ARE the model config. Serving a cached artefact
        # after a threshold change would report boundaries nobody asked for.
        run_shots_sub_stage(ctx, FADE_MP4)
        rerun = run_shots_sub_stage(ctx, FADE_MP4, config={"hard_cut_threshold": 15.0})
        assert rerun.cache_hit is False

    def test_the_artefact_is_written_and_reloadable(self, ctx: SubStageContext) -> None:
        result = run_shots_sub_stage(ctx, HARD_CUT_MP4)
        assert result.artefact_path.exists()
        assert len(result.artefact["shots"]) == 3

    def test_a_failure_leaves_the_sub_stage_resumable(self, ctx: SubStageContext, tmp_path: Path) -> None:
        junk = tmp_path / "broken.mp4"
        junk.write_bytes(b"nope")
        with pytest.raises(SubStageError):
            run_shots_sub_stage(ctx, junk)
        # No poisoned checkpoint: the real media must still be indexable.
        assert run_shots_sub_stage(ctx, HARD_CUT_MP4).cache_hit is False
