#!/usr/bin/env node
/*
 * Config-driven pre-write guardrails (PreToolUse: Edit | Write | MultiEdit).
 *
 * This is the PORTABLE engine. It contains NO project-specific rules of its own —
 * it reads them from `.claude/guardrails.rules.json` next to this file. That keeps
 * the engine reusable across every project while the *rules* are tailored per repo
 * (hand-written, or generated by the `/bootstrap-claude-pack` command).
 *
 * Lifecycle:
 *   - Reads the Claude Code PreToolUse payload from stdin.
 *   - Loads the rule set from $CLAUDE_PROJECT_DIR/.claude/guardrails.rules.json.
 *   - Evaluates each rule against the proposed file path + written content.
 *   - severity "warn"  -> exit 0, message on stderr (Claude sees it, write proceeds).
 *   - severity "block" -> exit 2, message on stderr (Claude must change course).
 *   - Any parse/IO problem -> exit 0 (fail open; a guardrail must never wedge work).
 *
 * Rule schema (see guardrails.rules.json for live examples):
 *   {
 *     "id":            "kebab-case-id",            // required, for diagnostics
 *     "severity":      "block" | "warn",           // required
 *     "tools":         ["Edit","Write","MultiEdit"],// optional; default = all three
 *     "filePattern":   "regex",                    // optional; path must match to fire
 *     "notFilePattern":"regex",                    // optional; path matching this is exempt
 *     "bodyPattern":   "regex",                    // optional; written content must match
 *     "absentPattern": "regex",                    // optional; fires only if body LACKS this
 *     "flags":         "i",                        // optional; regex flags for body/file patterns
 *     "message":       "guidance shown to Claude"  // required
 *   }
 *
 * A rule fires when ALL present conditions hold:
 *   tool matches  AND  filePattern matches path  AND  notFilePattern does NOT match path
 *   AND  bodyPattern matches body  AND  (absentPattern is missing OR not found in body).
 * A rule with neither bodyPattern nor absentPattern is a pure path rule (fires on any
 * write to a matching path) — handy for "never edit this directory".
 *
 * Two semantics worth knowing:
 *   - Claude Code passes an ABSOLUTE file_path (back-slashes normalized to "/"). So
 *     filePattern/notFilePattern must use "(^|/)foo" NOT "^foo" — a bare "^" anchor
 *     never matches an absolute path. Prefer mid-string anchors and a trailing "$".
 *   - "flags" applies to filePattern, notFilePattern AND bodyPattern (one shared field).
 *   - absentPattern is judged against the body PLUS the current on-disk file content,
 *     so a partial Edit whose snippet omits a required token is NOT wrongly blocked when
 *     that token already exists in the file. It is for "this file must contain X" rules.
 */

const fs = require("fs");
const path = require("path");

function failOpen() {
  process.exit(0);
}

let input;
try {
  input = JSON.parse(fs.readFileSync(0, "utf8"));
} catch (e) {
  failOpen();
}

const tool = input.tool_name || "";
const ti = input.tool_input || {};
const filePath = (ti.file_path || ti.path || "").replace(/\\/g, "/");
if (!filePath) failOpen();

// Collect every body chunk this call would write/edit.
const bodies = [];
if (typeof ti.new_string === "string") bodies.push(ti.new_string);
if (typeof ti.content === "string") bodies.push(ti.content);
if (Array.isArray(ti.edits)) {
  for (const e of ti.edits) {
    if (e && typeof e.new_string === "string") bodies.push(e.new_string);
  }
}
const body = bodies.join("\n");

// Locate the rule file relative to this hook (CLAUDE_PROJECT_DIR is most reliable).
const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();
const candidates = [
  path.join(projectDir, ".claude", "guardrails.rules.json"),
  path.join(__dirname, "..", "guardrails.rules.json"),
];

let config = null;
for (const c of candidates) {
  try {
    if (fs.existsSync(c)) {
      config = JSON.parse(fs.readFileSync(c, "utf8"));
      break;
    }
  } catch (e) {
    // Malformed config -> fail open (never block on a broken rule file), but say so
    // loudly: with the rules unparseable, ALL write-time protection (secret-blocking
    // included) is OFF until the file is fixed. This is the one signal the user gets.
    process.stderr.write(
      `guardrails: ENFORCEMENT DISABLED — could not parse ${c} (${e.message}). ` +
        `All guardrail rules are OFF until you fix this file. ` +
        `Validate with: node -e "JSON.parse(require('fs').readFileSync('${c.replace(/\\/g, "/")}','utf8'))"\n`
    );
    failOpen();
  }
}
if (!config || !Array.isArray(config.rules)) failOpen();

function safeRegex(src, flags) {
  if (typeof src !== "string") return null;
  try {
    return new RegExp(src, flags || "");
  } catch (e) {
    process.stderr.write(`guardrails: rule has invalid regex /${src}/ — skipped.\n`);
    return null;
  }
}

// Lazily read the target file's current content (pre-edit state on disk), cached.
// Used only by absentPattern rules so partial Edits aren't judged on the fragment alone.
let _existing = null;
function existingFileContent() {
  if (_existing !== null) return _existing;
  try {
    _existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : "";
  } catch (e) {
    _existing = "";
  }
  return _existing;
}

let blocked = false;
const warnings = [];

// Defensive: any unanticipated error during evaluation must fail open, never wedge a
// write. (A PreToolUse hook only blocks on exit 2; this makes that guarantee explicit
// rather than relying on an uncaught exception happening to exit 1.)
try {
for (const rule of config.rules) {
  if (!rule || typeof rule !== "object") continue;
  const sev = rule.severity === "block" ? "block" : "warn";
  const tools =
    Array.isArray(rule.tools) && rule.tools.length
      ? rule.tools
      : ["Edit", "Write", "MultiEdit"];
  // Skip the rule unless this tool is in its list. A missing/empty tool name
  // therefore matches nothing and fails open (never evaluates Edit/Write rules).
  if (!tools.includes(tool)) continue;

  const flags = rule.flags || "";

  if (rule.filePattern) {
    const re = safeRegex(rule.filePattern, flags);
    if (!re || !re.test(filePath)) continue;
  }
  if (rule.notFilePattern) {
    const re = safeRegex(rule.notFilePattern, flags);
    // An exemption we can't evaluate must skip the whole rule, not silently drop the
    // exemption — firing anyway risks a false BLOCK on a path the author meant to exempt.
    if (!re || re.test(filePath)) continue;
  }
  if (rule.bodyPattern) {
    const re = safeRegex(rule.bodyPattern, flags);
    if (!re || !re.test(body)) continue;
  }
  if (rule.absentPattern) {
    const re = safeRegex(rule.absentPattern, flags);
    // Fires only when the required pattern is ABSENT. Judge against the body PLUS the
    // current on-disk file, so a partial Edit that omits a token already present in the
    // file is not wrongly blocked. (existingFileContent is read lazily and cached.)
    if (re && re.test(body + "\n" + existingFileContent())) continue;
  }
  // A rule with no body/absent pattern is a pure path rule — it has already passed
  // the file gates above, so it fires.

  const id = rule.id || "(unnamed)";
  const msg = rule.message || "guardrail triggered";
  if (sev === "block") {
    process.stderr.write(`guardrail BLOCK [${id}]: ${msg}\n`);
    blocked = true;
  } else {
    warnings.push(`guardrail WARN [${id}]: ${msg}`);
  }
}
} catch (e) {
  process.stderr.write(`guardrails: evaluation error (${(e && e.message) || String(e)}); failing open.\n`);
  failOpen();
}

// Emit warnings (non-fatal) then decide exit code.
for (const w of warnings) process.stderr.write(w + "\n");
process.exit(blocked ? 2 : 0);
