#!/usr/bin/env node
/*
 * Config-driven pre-write guardrails (PreToolUse: Edit | Write | MultiEdit).
 *
 * This is the PORTABLE engine. It contains NO project-specific rules of its own —
 * it reads them from `.claude/guardrails.rules.json` next to this file. That keeps
 * the engine reusable across every project while the *rules* are tailored per repo
 * (hand-written, or generated by the `/bootstrap-claude-pack` command).
 *
 * Lifecycle:
 *   - Reads the Claude Code PreToolUse payload from stdin.
 *   - Loads the rule set from $CLAUDE_PROJECT_DIR/.claude/guardrails.rules.json.
 *   - Evaluates each rule against the proposed file path + written content.
 *   - severity "warn"  -> exit 0, message on stderr (Claude sees it, write proceeds).
 *   - severity "block" -> exit 2, message on stderr (Claude must change course).
 *   - Any parse/IO problem -> exit 0 (fail open; a guardrail must never wedge work).
 *
 * Rule schema (see guardrails.rules.json for live examples):
 *   {
 *     "id":            "kebab-case-id",            // required, for diagnostics
 *     "severity":      "block" | "warn",           // required
 *     "tools":         ["Edit","Write","MultiEdit"],// optional; default = those three plus NotebookEdit
 *     "filePattern":   "regex",                    // optional; path must match to fire
 *     "notFilePattern":"regex",                    // optional; path matching this is exempt
 *     "bodyPattern":   "regex",                    // optional; written content must match
 *     "absentPattern": "regex",                    // optional; fires only if body LACKS this
 *     "maxLines":      800,                        // optional; fires when the RESULTING file exceeds N lines and is not shrinking
 *     "flags":         "i",                        // optional; regex flags for body/file patterns
 *     "message":       "guidance shown to Claude"  // required
 *   }
 *
 * A rule fires when ALL present conditions hold:
 *   tool matches  AND  filePattern matches path  AND  notFilePattern does NOT match path
 *   AND  bodyPattern matches body  AND  (absentPattern is missing OR not found in body)
 *   AND  (maxLines is missing OR the resulting file has more than maxLines lines and grew).
 *   "{lines}" in a message is replaced with the resulting line count. Keep maxLines rules at
 *   severity "warn": size is a split signal, never a reason to block a write.
 * A rule with neither bodyPattern nor absentPattern is a pure path rule (fires on any
 * write to a matching path) — handy for "never edit this directory".
 *
 * Two semantics worth knowing:
 *   - Claude Code passes an ABSOLUTE file_path (back-slashes normalized to "/"). So
 *     filePattern/notFilePattern must use "(^|/)foo" NOT "^foo" — a bare "^" anchor
 *     never matches an absolute path. Prefer mid-string anchors and a trailing "$".
 *   - "flags" applies to filePattern, notFilePattern, bodyPattern AND absentPattern
 *     (one shared field).
 *   - For Write, absentPattern is judged against the replacement body alone. For Edit and
 *     MultiEdit, the hook applies the proposed replacements to the current file and judges
 *     the resulting content. An edit it cannot model unambiguously is diagnostic-skipped.
 */

const fs = require("fs");
const path = require("path");

function failOpen() {
  process.exit(0);
}
function writeErr(text) {
  try { fs.writeSync(2, text); } catch (e) { try { process.stderr.write(text); } catch (e2) { /* ignore */ } }
}

// Keep every fallible operation below one ultimate fail-open boundary. Individual
// diagnostics stay narrow; an unexpected engine error exits silently.
function main() {
let input;
try {
  input = JSON.parse(fs.readFileSync(0, "utf8")) || {};
} catch (e) {
  failOpen();
}

const tool = input.tool_name || "";
const ti = input.tool_input || {};
// NotebookEdit shares the "Edit" matcher but names its file notebook_path and its body new_source.
const rawFilePath = ti.file_path || ti.path || ti.notebook_path || "";
if (typeof rawFilePath !== "string" || !rawFilePath) failOpen();
const filePath = rawFilePath.replace(/\\/g, "/");

// Collect every body chunk this call would write/edit.
const bodies = [];
if (typeof ti.new_string === "string") bodies.push(ti.new_string);
if (typeof ti.new_source === "string") bodies.push(ti.new_source);
if (typeof ti.content === "string") bodies.push(ti.content);
if (Array.isArray(ti.edits)) {
  for (const e of ti.edits) {
    if (e && typeof e.new_string === "string") bodies.push(e.new_string);
  }
}
const body = bodies.join("\n");

// Locate the rule file relative to this hook (CLAUDE_PROJECT_DIR is most reliable).
const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();
const candidates = [
  path.join(projectDir, ".claude", "guardrails.rules.json"),
  path.join(__dirname, "..", "guardrails.rules.json"),
];

let config = null;
for (const c of candidates) {
  try {
    if (fs.existsSync(c)) {
      config = JSON.parse(fs.readFileSync(c, "utf8"));
      break;
    }
  } catch (e) {
    // Malformed config -> fail open (never block on a broken rule file), but say so
    // loudly: with the rules unparseable, ALL write-time protection (secret-blocking
    // included) is OFF until the file is fixed. This is the one signal the user gets.
    writeErr(
      `guardrails: ENFORCEMENT DISABLED — could not parse ${c} (${e.message}). ` +
        `All guardrail rules are OFF until you fix this file. ` +
        `Validate with: node -e "JSON.parse(require('fs').readFileSync('${c.replace(/\\/g, "/")}','utf8'))"\n`
    );
    failOpen();
  }
}
if (!config || !Array.isArray(config.rules)) failOpen();

function safeRegex(src, flags, ruleId, field) {
  if (typeof src !== "string") {
    writeErr(
      `guardrails: rule "${ruleId}" has non-string ${field} in ` +
        `.claude/guardrails.rules.json; this rule did not run. Fix the pattern before retrying.\n`
    );
    return null;
  }
  try {
    return new RegExp(src, flags || "");
  } catch (e) {
    writeErr(
      `guardrails: rule "${ruleId}" has invalid ${field} pattern /${src}/ in ` +
        `.claude/guardrails.rules.json; this rule did not run. Fix the pattern before retrying.\n`
    );
    return null;
  }
}

function safeFlags(flags, ruleId) {
  if (typeof flags !== "string") {
    writeErr(
      `guardrails: rule "${ruleId}" has non-string shared flags in ` +
        `.claude/guardrails.rules.json; this rule did not run. Fix flags before retrying.\n`
    );
    return null;
  }
  try {
    new RegExp("", flags);
    return flags;
  } catch (e) {
    writeErr(
      `guardrails: rule "${ruleId}" has invalid shared flags "${flags}" in ` +
        `.claude/guardrails.rules.json; this rule did not run. Fix flags before retrying.\n`
    );
    return null;
  }
}

// Lazily derive the file content that the proposed operation would leave behind.
// Edit rejects an ambiguous old_string unless replace_all is true; mirror that rule
// here rather than treating pre-edit content as evidence the required token survives.
let _existingLoaded = false;
let _existing = null;
function existingFileContent() {
  if (_existingLoaded) return _existing;
  _existingLoaded = true;
  try {
    _existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;
  } catch (e) {
    _existing = null;
  }
  return _existing;
}

function applyEdit(content, edit) {
  if (
    !edit ||
    typeof edit !== "object" ||
    typeof edit.old_string !== "string" ||
    typeof edit.new_string !== "string" ||
    edit.old_string.length === 0
  ) {
    return null;
  }
  const first = content.indexOf(edit.old_string);
  if (first === -1) return null;
  if (edit.replace_all === true) {
    return content.split(edit.old_string).join(edit.new_string);
  }
  if (content.indexOf(edit.old_string, first + edit.old_string.length) !== -1) {
    return null;
  }
  return (
    content.slice(0, first) +
    edit.new_string +
    content.slice(first + edit.old_string.length)
  );
}

let _resultingLoaded = false;
let _resulting = null;
function resultingFileContent() {
  if (_resultingLoaded) return _resulting;
  _resultingLoaded = true;
  let content = existingFileContent();
  if (content === null) return null;
  const edits =
    tool === "Edit" ? [ti] : tool === "MultiEdit" && Array.isArray(ti.edits) ? ti.edits : null;
  if (!edits || !edits.length) return null;
  for (const edit of edits) {
    content = applyEdit(content, edit);
    if (content === null) return null;
  }
  _resulting = content;
  return _resulting;
}

let blocked = false;
const warnings = [];

// Defensive: any unanticipated error during evaluation must fail open, never wedge a
// write. (A PreToolUse hook only blocks on exit 2; this makes that guarantee explicit
// rather than relying on an uncaught exception happening to exit 1.)
try {
for (const rule of config.rules) {
  if (!rule || typeof rule !== "object") continue;
  const sev = rule.severity === "block" ? "block" : "warn";
  const tools =
    Array.isArray(rule.tools) && rule.tools.length
      ? rule.tools
      : ["Edit", "Write", "MultiEdit", "NotebookEdit"];
  // Skip the rule unless this tool is in its list. A missing/empty tool name
  // therefore matches nothing and fails open (never evaluates Edit/Write rules).
  if (!tools.includes(tool)) continue;

  const id = rule.id || "(unnamed)";
  const configuredFlags =
    rule.flags === undefined || rule.flags === null ? "" : rule.flags;
  const flags = safeFlags(configuredFlags, id);
  if (flags === null) continue;

  if (Object.prototype.hasOwnProperty.call(rule, "filePattern")) {
    const re = safeRegex(rule.filePattern, flags, id, "filePattern");
    if (!re || !re.test(filePath)) continue;
  }
  if (Object.prototype.hasOwnProperty.call(rule, "notFilePattern")) {
    const re = safeRegex(rule.notFilePattern, flags, id, "notFilePattern");
    // An exemption we can't evaluate must skip the whole rule, not silently drop the
    // exemption — firing anyway risks a false BLOCK on a path the author meant to exempt.
    if (!re || re.test(filePath)) continue;
  }
  if (Object.prototype.hasOwnProperty.call(rule, "bodyPattern")) {
    const re = safeRegex(rule.bodyPattern, flags, id, "bodyPattern");
    if (!re || !re.test(body)) continue;
  }
  if (Object.prototype.hasOwnProperty.call(rule, "absentPattern")) {
    const re = safeRegex(rule.absentPattern, flags, id, "absentPattern");
    // An absent condition we cannot evaluate must skip the whole rule; firing would risk
    // a false block when the rule author's required pattern is invalid.
    if (!re) continue;
    // Write replaces the whole file. Partial edits are applied in memory so both a
    // surviving token and removal of the only token are evaluated against final content.
    const contentAfterWrite = tool === "Write" ? body : resultingFileContent();
    if (contentAfterWrite === null) {
      writeErr(
        `guardrails: rule "${id}" could not evaluate resulting content after ${tool}; ` +
          `this rule did not run. Retry with an unambiguous edit.\n`
      );
      continue;
    }
    if (re.test(contentAfterWrite)) continue;
  }
  let lineCount = null;
  if (Object.prototype.hasOwnProperty.call(rule, "maxLines")) {
    const max = rule.maxLines;
    if (!Number.isInteger(max) || max <= 0) {
      writeErr(`guardrails: rule "${id}" has an invalid maxLines (positive integer required); this rule did not run.\n`);
      continue;
    }
    // Only Write and Edit/MultiEdit can be modelled; an unreadable or ambiguous edit is
    // nothing to judge — skip silently (a size warn is never worth a diagnostic).
    const after = tool === "Write" ? body : resultingFileContent();
    if (after === null) continue;
    lineCount = after.split("\n").length - (after.endsWith("\n") ? 1 : 0);
    if (lineCount <= max) continue;
    // Not-shrinking guard: an edit that reduces (or holds) the count is the split in
    // progress — nagging it would punish exactly the fix the rule asks for.
    const before = existingFileContent();
    if (before !== null && lineCount <= before.split("\n").length) continue;
  }
  // A rule with no body/absent/size pattern is a pure path rule — it has already passed
  // the file gates above, so it fires.

  const msg = (rule.message || "guardrail triggered").replace("{lines}", lineCount === null ? "" : String(lineCount));
  if (sev === "block") {
    writeErr(`guardrail BLOCK [${id}]: ${msg}\n`);
    blocked = true;
  } else {
    warnings.push(`guardrail WARN [${id}]: ${msg}`);
  }
}
} catch (e) {
  writeErr(
    `guardrails: ENFORCEMENT SKIPPED after an evaluation error ` +
      `(${(e && e.message) || String(e)}). Your edit continued without complete guardrail protection. ` +
      `Run /doctor before the next edit; if this repeats, inspect .claude/guardrails.rules.json.\n`
  );
  failOpen();
}

// Emit warnings (non-fatal) then decide exit code. writeSync: process.exit() right after an
// async pipe write can truncate the reason the person needs to see.
for (const w of warnings) writeErr(w + "\n");
process.exit(blocked ? 2 : 0);
}

try {
  main();
} catch (e) {
  failOpen();
}
