import { ok, strictEqual } from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, before, describe, it } from 'node:test';

import { orphanMirrors, registryEntry, skillsSync } from '../src/commands/skills-sync.js';
import type { SkillFrontmatter } from '../src/skills.js';

/**
 * The DESTRUCTIVE branch of `skills sync`, which had no test at all — and both Phase
 * 5 reviewers said so.
 *
 * The mirror root is OUTSIDE the self-rooted workspace and holds the pack's own
 * hand-written skills, so a recursive force-delete guarded only by a name prefix
 * fails CLAUDE.md golden rule 3 ("never destroy what you didn't create"). Removal now
 * needs three things: the `cutdown-` prefix, POSITIVE evidence this command wrote the
 * directory (the generated banner in its `SKILL.md`), and an explicit `--prune`.
 *
 * A separate file from `skills-sync.test.ts` because these tests need a temp mirror
 * root and the others deliberately run read-only against the real tree.
 */

const NL = '\n';
const BANNER = 'DO NOT EDIT — generated by `cutdown skills sync`';

/**
 * Assembled from parts so the test source carries no escaped newlines.
 *
 * The generated arm reproduces the REAL generator's anchor exactly — a `---` +
 * `name: ` opening plus `<!-- <banner>. Edit cutdown/skills/<name>/SKILL.md instead. -->`.
 * Ownership is checked against that anchor rather than a bare `includes(banner)`, so a
 * hand-written skill that merely QUOTES the banner is not classified as generated —
 * and a fixture that only approximated the generated shape would not exercise that.
 */
const skillMd = (name: string, generated: boolean): string =>
  [
    '---',
    `name: ${name}`,
    '---',
    '',
    generated
      ? `<!-- ${BANNER}. Edit cutdown/skills/${name.replace('cutdown-', '')}/SKILL.md instead. -->`
      : 'Somebody wrote this by hand, and it must survive a prune.',
    '',
  ].join(NL);

const frontmatter: SkillFrontmatter = {
  name: 'live',
  skillVersion: '1.0.0',
  description: 'A description long enough to be invocation-worthy for a conversational agent to pick.',
  entrypoint: ['node', 'dist/src/main.js'],
  execution: 'sync',
  inputSchema: './schema/input.json',
  outputSchema: './schema/output.json',
  contractsUsed: ['platform-edl-v1'],
  sideEffects: ['reads-project-data'],
  timeoutSeconds: 60,
};

describe('orphan mirrors are CLASSIFIED before anything is removed', () => {
  let root: string;

  const seed = (name: string, generated: boolean): string => {
    const dir = join(root, name);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'SKILL.md'), skillMd(name, generated));
    return dir;
  };

  before(() => {
    root = mkdtempSync(join(tmpdir(), 'cutdown-mirror-'));
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it('marks a GENERATED orphan removable and a hand-written one NOT removable', () => {
    seed('cutdown-gone', true);
    seed('cutdown-handwritten', false);

    const byName = new Map(orphanMirrors([], root).map((o) => [o.name, o]));
    strictEqual(byName.get('cutdown-gone')?.generated, true);
    strictEqual(byName.get('cutdown-handwritten')?.generated, false);
    ok(
      byName.get('cutdown-handwritten')?.reason.includes('golden rule 3'),
      'the reason names the rule, so nobody "fixes" it by loosening the check',
    );
  });

  it('ignores a directory that is not `cutdown-` prefixed — the pack owns those', () => {
    mkdirSync(join(root, 'using-the-pack'), { recursive: true });
    ok(!orphanMirrors([], root).some((o) => o.name === 'using-the-pack'));
  });

  it('classifies a `cutdown-` FILE rather than throwing on it', () => {
    // `withFileTypes` rather than `statSync`: the first cut threw on a broken symlink
    // and killed the whole sync, and `statSync` follows a symlink so one would have
    // been classified as a directory to descend into.
    writeFileSync(join(root, 'cutdown-stray.txt'), 'not a mirror');
    const stray = orphanMirrors([], root).find((o) => o.name === 'cutdown-stray.txt');
    ok(stray !== undefined);
    strictEqual(stray.generated, false);
    ok(stray.reason.includes('not a directory'));
  });

  it('reports a `cutdown-` directory with no SKILL.md as unremovable', () => {
    mkdirSync(join(root, 'cutdown-empty'), { recursive: true });
    const empty = orphanMirrors([], root).find((o) => o.name === 'cutdown-empty');
    strictEqual(empty?.generated, false);
    ok(empty.reason.includes('no readable SKILL.md'));
  });

  it('does NOT classify a hand-written skill that merely QUOTES the banner as generated', () => {
    // The reason ownership is anchored rather than a bare `includes`: documentation
    // about the mirror format legitimately contains the banner text.
    const dir = join(root, 'cutdown-docs-about-mirrors');
    mkdirSync(dir, { recursive: true });
    writeFileSync(
      join(dir, 'SKILL.md'),
      [
        '---',
        'name: cutdown-docs-about-mirrors',
        '---',
        '',
        `Generated mirrors carry the line "${BANNER}" near the top of the file.`,
        '',
      ].join(NL),
    );
    const entry = orphanMirrors([], root).find((o) => o.name === 'cutdown-docs-about-mirrors');
    strictEqual(entry?.generated, false, 'quoting the banner is not evidence of authorship');
  });

  it('does NOT list a mirror whose skill is still live', () => {
    seed('cutdown-live', true);
    ok(!orphanMirrors([registryEntry(frontmatter)], root).some((o) => o.name === 'cutdown-live'));
  });
});

describe('sync writes into an injected mirror root, and prunes only on request', () => {
  let root: string;
  /**
   * The registry is injected for the same reason the mirror root is. Until it
   * was, every test in this block rewrote the REPO's real `skills/registry.json`
   * — a no-op only because the content regenerated identically, which is luck,
   * not isolation: one mid-edit skill and the suite would have committed a
   * registry nobody generated on purpose.
   */
  let registryPath: string;

  before(() => {
    root = mkdtempSync(join(tmpdir(), 'cutdown-mirror-write-'));
    registryPath = join(root, 'registry.json');
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it('generates every mirror into the injected root', () => {
    const outcome = skillsSync({ mirrorRoot: root, registryPath });
    strictEqual(outcome.problems.length, 0, JSON.stringify(outcome.problems));
    ok(existsSync(join(root, 'cutdown-approve', 'SKILL.md')));
    ok(existsSync(join(root, 'cutdown-package', 'SKILL.md')));
    strictEqual(outcome.removed.length, 0, 'a first run removes nothing');
  });

  it('is idempotent against the injected root too', () => {
    strictEqual(skillsSync({ mirrorRoot: root, registryPath }).written.length, 0);
  });

  it('REPORTS a generated orphan without --prune, and does not delete it', () => {
    const orphan = join(root, 'cutdown-retired');
    mkdirSync(orphan, { recursive: true });
    writeFileSync(join(orphan, 'SKILL.md'), skillMd('cutdown-retired', true));

    const outcome = skillsSync({ mirrorRoot: root, registryPath });
    strictEqual(outcome.removed.length, 0, 'a delete is not undoable, so it is opt-in');
    ok(outcome.warnings.some((w) => w.skill.includes('cutdown-retired') && w.problem.includes('--prune')));
    ok(existsSync(orphan), 'still there');
  });

  it('removes a generated orphan WITH --prune', () => {
    const outcome = skillsSync({ mirrorRoot: root, prune: true, registryPath });
    ok(outcome.removed.some((r) => r.includes('cutdown-retired')));
    ok(!existsSync(join(root, 'cutdown-retired')));
  });

  it('REFUSES to remove a hand-written cutdown-* mirror even with --prune', () => {
    // The load-bearing case. A name prefix is a convention; the generated banner is
    // evidence. Without this, a hand-authored `cutdown-something` was deleted silently
    // on the next sync — a directory this command never created.
    const handwritten = join(root, 'cutdown-mine');
    mkdirSync(handwritten, { recursive: true });
    writeFileSync(join(handwritten, 'SKILL.md'), skillMd('cutdown-mine', false));

    const outcome = skillsSync({ mirrorRoot: root, prune: true, registryPath });
    ok(existsSync(handwritten), 'a directory this command did not create is never removed');
    strictEqual(outcome.removed.length, 0);
    ok(
      outcome.problems.some((p) => p.skill.includes('cutdown-mine')),
      'and it is reported as a PROBLEM, not silently tolerated',
    );
  });
});
