import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

import { createAjv, formatAjvErrors, listContractSchemas, schemaName } from '@cutdown/contracts';

import { SKILLS_ROOT, WORKSPACE_ROOT } from '../paths.js';
import { listSkillNames, readSkill, type SkillFrontmatter } from '../skills.js';

/**
 * `cutdown skills sync` — the registry and the `.claude` mirror (tech-spec §6.3/§6.4,
 * decisions.md D-15).
 *
 * From tech-spec §15 step 9 onward, Claude Code is the operator surface. That only
 * works if the mirror is GENERATED: `.claude/skills/cutdown-<name>/SKILL.md` is
 * derived from `skills/<name>/SKILL.md` and never hand-edited, so there is exactly
 * one source of truth for a skill's behaviour regardless of which of the four
 * callers picks it up.
 *
 * Three properties this command owes:
 *
 *   1. **Strict validation, no exceptions** (D-15). Every frontmatter field is
 *      checked and unknown keys are rejected. A typo'd `timeoutSecond` would
 *      otherwise leave a skill running on a default nobody chose.
 *   2. **Dangling `contractsUsed` fails the sync.** That failure is what makes a
 *      contract major bump compile-time-visible to every dependent skill, instead
 *      of surfacing three stages later as a malformed artefact.
 *   3. **Idempotent.** A second run with nothing changed writes nothing and reports
 *      no diff. Generated output that churns on every run trains people to ignore
 *      its diffs, and then a real change hides in the noise.
 *
 * ## Why the mirror names are prefixed
 *
 * This repo already has pack skills called `review`, `plan` and `validate`. An
 * unprefixed mirror would collide with them, and the collision would be resolved
 * by whichever loaded last — silently running the wrong skill. `cutdown-` makes the
 * namespace explicit (tech-spec §2).
 */

const MIRROR_PREFIX = 'cutdown-';
const META_SCHEMA = join(SKILLS_ROOT, 'meta-schema.json');
const REGISTRY = join(SKILLS_ROOT, 'registry.json');
/** The mirror lives in the REPO's `.claude/`, one level above the cutdown workspace. */
const MIRROR_ROOT = join(WORKSPACE_ROOT, '..', '.claude', 'skills');

const GENERATED_BANNER = 'DO NOT EDIT — generated by `cutdown skills sync`';

export interface SyncProblem {
  readonly skill: string;
  readonly problem: string;
}

export interface SyncOutcome {
  readonly problems: readonly SyncProblem[];
  readonly warnings: readonly SyncProblem[];
  /** Files whose content changed (or that were created) this run. */
  readonly written: readonly string[];
  /** Mirror directories removed because their skill no longer exists. */
  readonly removed: readonly string[];
  readonly skillCount: number;
}

export interface RegistryEntry {
  readonly name: string;
  readonly mirrorName: string;
  readonly skillVersion: string;
  readonly description: string;
  readonly entrypoint: readonly string[];
  readonly execution: 'sync' | 'async';
  readonly inputSchema: string;
  readonly outputSchema: string;
  readonly contractsUsed: readonly string[];
  readonly sideEffects: readonly string[];
  readonly timeoutSeconds: number;
  readonly heartbeatSeconds?: number;
}

/**
 * Compare generated text to what is on disk WITHOUT letting line endings decide.
 *
 * This repo has `core.autocrlf=true`, so a checkout can legitimately hold CRLF while
 * the generator emits LF. A raw `===` then reports every generated file as changed,
 * making `skills sync --check` permanently stale on a tree nobody has touched and
 * turning `sync` into an unconditional rewrite.
 *
 * TWO attributes files pin `eol=lf`, covering different halves, and it matters which:
 * `cutdown/.gitattributes` covers `cutdown/**` (the SOURCE `SKILL.md` files), and the
 * REPO-ROOT `.gitattributes` covers `.claude/**` (the generated MIRROR, which lives
 * above the cutdown workspace and was uncovered until round 4 pointed it out). For
 * files under `cutdown/`, this normalisation is a fallback for checkouts predating
 * those files; for the mirror it was the only protection there was.
 */
const normaliseNewlines = (text: string): string => text.split('\r\n').join('\n');

/**
 * Write a file only when its content would change.
 *
 * This is what makes the whole command idempotent, and it is a content comparison
 * rather than a timestamp one on purpose: `build:contracts --check`-style tooling
 * and a human reading `git status` both want "nothing changed" to mean nothing
 * changed.
 */
function writeIfChanged(path: string, content: string, written: string[]): void {
  if (existsSync(path) && normaliseNewlines(readFileSync(path, 'utf8')) === normaliseNewlines(content)) return;
  mkdirSync(join(path, '..'), { recursive: true });
  writeFileSync(path, content, 'utf8');
  written.push(relative(WORKSPACE_ROOT, path).split('\\').join('/'));
}

/**
 * Compile the strict meta-schema on the contracts package's configured Ajv.
 *
 * Reusing `createAjv()` rather than constructing a second instance keeps ONE set
 * of validation settings in the workspace: strict mode on, formats registered, and
 * the `schemaVersion`/`changelog` annotation keywords declared. A second instance
 * with slightly different options is how two validators come to disagree about the
 * same document.
 */
function metaValidator() {
  return createAjv().compile(JSON.parse(readFileSync(META_SCHEMA, 'utf8')) as object);
}

/**
 * The generated `.claude` mirror body (tech-spec §6.3).
 *
 * A conversational invocation (`/cutdown-propose make 3 variants for job X`)
 * arrives as free text, so the body is a four-step procedure rather than a command
 * line. Step 1 is the load-bearing one: build a request valid against the skill's
 * own `input.json` and ASK for any missing required field. An agent that guessed a
 * missing `accountId` or a missing `--by` name would be inventing the very data the
 * contracts exist to pin down.
 */
export function mirrorBody(front: SkillFrontmatter, mirrorName: string): string {
  // Two roots are in play and the body has to be explicit about which is which, or
  // the round-trip cannot work. An agent runs at the REPO root, so the files it reads
  // are `cutdown/...`-prefixed. But `pnpm -C cutdown` runs the CLI with cwd =
  // `<repo>/cutdown`, and `resolveUserPath` resolves `--input` against cwd — so a
  // `cutdown/`-prefixed path handed to step 3 double-prefixes to
  // `<repo>/cutdown/cutdown/...`.
  //
  // Round 1 fixed step 2 and broke step 3 the same way. The fix is to stop mixing
  // them: the Write step uses the repo-relative path, and step 3 passes the
  // `cutdown/`-RELATIVE form, with each labelled.
  const repoRelativeRequest = 'cutdown/project-data/jobs/<job-id>/requests/<ulid>.json';
  const cliRelativeRequest = 'project-data/jobs/<job-id>/requests/<ulid>.json';
  const cliRelativeResult = 'project-data/jobs/<job-id>/results/<ulid>.json';
  return `---
name: ${mirrorName}
description: ${front.description}
allowed-tools: Bash(pnpm -C cutdown cutdown:*), Read, Write
---

# ${mirrorName} — generated mirror of \`cutdown/skills/${front.name}\`

<!-- ${GENERATED_BANNER}. Edit cutdown/skills/${front.name}/SKILL.md instead. -->

This wrapper exists because a conversational ask (\`/${mirrorName} ...\`) arrives as
free text, and the skill's contract is a JSON request validated against a schema
(tech-spec §6.2). Your job is to bridge the two **without inventing anything**.

## Two roots, and which is which

You are at the **repo root**, so files you Read and Write are \`cutdown/…\`-prefixed.
The CLI runs with \`-C cutdown\`, so paths you pass it are relative to \`cutdown/\`
(the same file, one prefix shorter). Getting this wrong is the difference between a
working invocation and \`ENOENT … cutdown/cutdown/…\`.

## Do this, in order

1. **Author the request.** Read \`cutdown/skills/${front.name}/schema/input.json\` and
   build an object that satisfies it from the user's ask. If a **required** field is
   missing from what they said, **ask them for it** — do not infer, default, or
   invent it. The required fields are the ones the pipeline cannot proceed honestly
   without.
2. **Write it** to \`${repoRelativeRequest}\` (repo-relative — this is a Write).
   Requests are kept so an invocation can be reproduced from the run log.
3. **Run it** (paths here are relative to \`cutdown/\`, so drop the \`cutdown/\` prefix):
   \`\`\`
   pnpm -C cutdown cutdown skills run ${front.name} --input ${cliRelativeRequest} --output ${cliRelativeResult}
   \`\`\`
4. **Report the result.** On exit 0, read the result JSON (at
   \`cutdown/${cliRelativeResult}\`) and summarise it. On a non-zero exit, the skill
   wrote a structured error object to stderr —
   \`{code, message, skill, skillVersion, details?}\`. **Surface that object**, not a
   paraphrase and not a stack trace: exit 2 means the request was invalid (fix the
   request), exit 3 means the skill could not do the work (the message says why).

## What this skill is

${front.description}

| | |
|---|---|
| skill version | \`${front.skillVersion}\` |
| execution | \`${front.execution}\`${front.execution === 'async' ? ' — long-running; Stage C returns an operation handle' : ''} |
| timeout | ${String(front.timeoutSeconds)}s |
| side effects | ${front.sideEffects.length === 0 ? 'none (pure computation)' : front.sideEffects.join(', ')} |
| contracts | ${front.contractsUsed.join(', ')} |

Read \`cutdown/skills/${front.name}/SKILL.md\` for the behaviour, the refusals, and
why each one exists. That file is the source of truth; this one is generated from it.
`;
}

/**
 * Everything `skills sync` DECIDES about one skill, as a pure function.
 *
 * Split out from the I/O so the rules can be tested without a filesystem and
 * without writing into the repo's own `.claude/`. The three checks a JSON Schema
 * cannot make live here, and each has a reason a comment cannot carry:
 *
 *   - **name === directory.** The CLI, the local runner and the mirror all address
 *     a skill by directory, so a mismatch means three callers disagree about which
 *     skill they ran.
 *   - **`contractsUsed` resolves.** This failure is the POINT of §6.4: a contract
 *     major bump has to be visible HERE, not three stages later as a malformed
 *     artefact.
 *   - **the declared schemas exist.** A skill whose `input.json` is missing fails
 *     at every invocation instead of at sync time.
 */
export function checkFrontmatter(
  frontmatter: SkillFrontmatter,
  context: {
    directoryName: string;
    validate: (value: unknown) => boolean;
    validationErrors?: () => string;
    contractNames: ReadonlySet<string>;
    schemaExists: (relativePath: string) => boolean;
  },
): { problems: SyncProblem[]; warnings: SyncProblem[] } {
  const skill = context.directoryName;
  const problems: SyncProblem[] = [];
  const warnings: SyncProblem[] = [];

  if (!context.validate(frontmatter)) {
    problems.push({
      skill,
      problem: `frontmatter does not satisfy skills/meta-schema.json (strict — D-15): ${context.validationErrors?.() ?? '(no detail)'}`,
    });
    // Every check below reads fields the schema has just declared untrustworthy.
    return { problems, warnings };
  }

  if (frontmatter.name !== skill) {
    problems.push({
      skill,
      problem: `frontmatter declares name "${frontmatter.name}" but the directory is "${skill}". The CLI, the runner and the mirror all address a skill by directory, so a mismatch means three callers disagree about which skill they ran.`,
    });
  }

  const dangling = frontmatter.contractsUsed.filter((contract) => !context.contractNames.has(contract));
  if (dangling.length > 0) {
    problems.push({
      skill,
      problem: `contractsUsed names ${dangling.join(', ')}, which have no schema under packages/contracts/schemas/. This failure is the POINT (tech-spec §6.4): a contract major bump must be visible to every dependent skill here, rather than surfacing three stages later as a malformed artefact.`,
    });
  }

  for (const [field, value] of [['inputSchema', frontmatter.inputSchema], ['outputSchema', frontmatter.outputSchema]] as const) {
    if (!context.schemaExists(value)) {
      problems.push({ skill, problem: `${field} points at ${value}, which does not exist` });
    }
  }

  if (frontmatter.execution === 'async' && frontmatter.heartbeatSeconds === undefined) {
    // A warning, not a failure: it only bites at Stage B, and failing the Phase 0
    // sync over a Stage B field would block work for a problem nobody has yet.
    warnings.push({
      skill,
      problem: 'declares `execution: async` but no `heartbeatSeconds`. The Temporal activity wrapper needs one at Stage B; harmless at Phase 0 because the local runner simply waits.',
    });
  }

  return { problems, warnings };
}

/** The registry row for a validated skill. Sorted lists so the file is stable. */
export function registryEntry(frontmatter: SkillFrontmatter): RegistryEntry {
  return {
    name: frontmatter.name,
    mirrorName: `${MIRROR_PREFIX}${frontmatter.name}`,
    skillVersion: frontmatter.skillVersion,
    description: frontmatter.description,
    entrypoint: frontmatter.entrypoint,
    execution: frontmatter.execution,
    inputSchema: frontmatter.inputSchema,
    outputSchema: frontmatter.outputSchema,
    contractsUsed: [...frontmatter.contractsUsed].sort(),
    sideEffects: [...frontmatter.sideEffects].sort(),
    timeoutSeconds: frontmatter.timeoutSeconds,
    ...(frontmatter.heartbeatSeconds === undefined ? {} : { heartbeatSeconds: frontmatter.heartbeatSeconds }),
  };
}

/** A removal target must be exactly one level below its root. */
function assertDirectChild(root: string, name: string): void {
  if (/[/\\]/.test(name) || name === '.' || name === '..') {
    throw new Error(`Refusing to remove ${JSON.stringify(name)}: a mirror name must be a single path component.`);
  }
  const resolvedRoot = resolve(root);
  const resolvedTarget = resolve(join(root, name));
  if (join(resolvedRoot, name) !== resolvedTarget) {
    throw new Error(`Refusing to remove ${resolvedTarget}: it is not a direct child of ${resolvedRoot}.`);
  }
}

/**
 * Validate every skill, regenerate `registry.json`, and regenerate the mirror.
 *
 * Nothing is written until every skill has validated. A sync that wrote half a
 * registry and then failed would leave the mirror describing a skill set that does
 * not exist — the same partial-commit failure the rest of the pipeline refuses.
 */
export function skillsSync(
  options: {
    check?: boolean;
    /** Remove generated orphan mirrors. Off by default: a delete is not undoable. */
    prune?: boolean;
    /** Injected so the write and delete branches are testable against a temp directory. */
    mirrorRoot?: string;
    /**
     * Injected for the same reason as `mirrorRoot`, and for the same reason it
     * was a gap: only the mirror root was injectable, so every test exercising
     * the write branch also rewrote the REPO's real `skills/registry.json`. It
     * happened to be a no-op because the content regenerated identically — but a
     * test that writes into the working tree is one mid-edit skill away from
     * committing a registry nobody generated on purpose.
     */
    registryPath?: string;
  } = {},
): SyncOutcome {
  const mirrorRoot = options.mirrorRoot ?? MIRROR_ROOT;
  const registryPath = options.registryPath ?? REGISTRY;
  const prune = options.prune === true;
  const validate = metaValidator();
  const contractNames = new Set(listContractSchemas().map((file) => schemaName(file)));
  const problems: SyncProblem[] = [];
  const warnings: SyncProblem[] = [];
  // Frontmatter is kept ALONGSIDE the registry entry rather than reconstructed
  // from it for mirror generation: a round-trip through the entry would be a second
  // representation of the same data, and the two would drift the first time a field
  // was added to one and not the other.
  const validated: { entry: RegistryEntry; frontmatter: SkillFrontmatter }[] = [];

  for (const name of listSkillNames()) {
    let frontmatter: SkillFrontmatter;
    try {
      frontmatter = readSkill(name).frontmatter;
    } catch (error) {
      problems.push({ skill: name, problem: `SKILL.md could not be read: ${(error as Error).message}` });
      continue;
    }

    const checked = checkFrontmatter(frontmatter, {
      directoryName: name,
      validate: (value: unknown) => validate(value) as boolean,
      validationErrors: () => formatAjvErrors(validate.errors),
      contractNames,
      schemaExists: (relative) => existsSync(join(SKILLS_ROOT, name, relative.replace(/^\.\//, ''))),
    });
    problems.push(...checked.problems);
    warnings.push(...checked.warnings);
    if (checked.problems.length > 0) continue;

    validated.push({ entry: registryEntry(frontmatter), frontmatter });
  }

  // Fail closed BEFORE writing anything. A half-written registry would describe a
  // skill set that does not exist.
  if (problems.length > 0) {
    return { problems, warnings, written: [], removed: [], skillCount: validated.length };
  }

  validated.sort((a, b) => (a.entry.name < b.entry.name ? -1 : a.entry.name > b.entry.name ? 1 : 0));
  const entries = validated.map((v) => v.entry);

  const registry = {
    _generated: GENERATED_BANNER,
    registryVersion: '1.0.0',
    metaSchema: './meta-schema.json',
    mirrorPrefix: MIRROR_PREFIX,
    skills: entries,
  };
  const registryJson = `${JSON.stringify(registry, null, 2)}\n`;

  const written: string[] = [];
  const removed: string[] = [];

  if (options.check === true) {
    // `--check` compares without writing, so it can be an entry-gate command.
    const stale: string[] = [];
    if (!existsSync(registryPath) || readFileSync(registryPath, 'utf8') !== registryJson) stale.push('skills/registry.json');
    for (const { entry, frontmatter } of validated) {
      const path = join(mirrorRoot, entry.mirrorName, 'SKILL.md');
      if (!existsSync(path) || readFileSync(path, 'utf8') !== mirrorBody(frontmatter, entry.mirrorName)) {
        stale.push(`.claude/skills/${entry.mirrorName}/SKILL.md`);
      }
    }
    for (const orphan of orphanMirrors(entries, mirrorRoot)) {
      stale.push(`.claude/skills/${orphan.name} (orphan — ${orphan.reason})`);
    }
    return {
      problems: stale.map((file) => ({ skill: file, problem: 'stale — run `cutdown skills sync`' })),
      warnings,
      written: [],
      removed: [],
      skillCount: entries.length,
    };
  }

  writeIfChanged(registryPath, registryJson, written);
  for (const { entry, frontmatter } of validated) {
    writeIfChanged(join(mirrorRoot, entry.mirrorName, 'SKILL.md'), mirrorBody(frontmatter, entry.mirrorName), written);
  }

  // A mirror for a skill that no longer exists is worse than a missing one: an
  // agent would invoke it and get a SKILL_NOT_FOUND from the CLI. But removal
  // requires positive evidence this command wrote it — see `orphanMirrors`.
  const unownedOrphans: SyncProblem[] = [];
  for (const orphan of orphanMirrors(entries, mirrorRoot)) {
    if (!orphan.generated) {
      unownedOrphans.push({ skill: `.claude/skills/${orphan.name}`, problem: orphan.reason });
      continue;
    }
    if (!prune) {
      warnings.push({
        skill: `.claude/skills/${orphan.name}`,
        problem: 'is a generated mirror with no source skill. Pass --prune to remove it; reporting rather than deleting by default, because a delete is not undoable.',
      });
      continue;
    }
    const target = join(mirrorRoot, orphan.name);
    // Belt to the name-prefix braces: the removal target must be a direct child of
    // the mirror root, so a name carrying a separator can never widen the blast
    // radius beyond one directory.
    assertDirectChild(mirrorRoot, orphan.name);
    rmSync(target, { recursive: true, force: true });
    removed.push(`.claude/skills/${orphan.name}`);
  }

  return { problems: unownedOrphans, warnings, written, removed, skillCount: entries.length };
}

export interface OrphanMirror {
  readonly name: string;
  /** True only when the directory carries this command's own generated banner. */
  readonly generated: boolean;
  readonly reason: string;
}

/**
 * `cutdown-*` mirror directories with no corresponding skill.
 *
 * Classified, not just listed. Removal requires POSITIVE evidence that this command
 * wrote the directory — its `SKILL.md` must carry `GENERATED_BANNER` — because
 * `MIRROR_ROOT` is outside the self-rooted workspace and holds the pack's own
 * hand-written skills. A name prefix is a naming convention, and CLAUDE.md golden
 * rule 3 ("never destroy what you didn't create") is not satisfied by a convention:
 * a hand-authored `cutdown-something` would have been deleted without a prompt.
 *
 * `withFileTypes` rather than `statSync`, so a broken symlink is classified instead
 * of throwing and killing the whole sync, and a symlink is never treated as a
 * directory to descend into.
 */
export function orphanMirrors(entries: readonly RegistryEntry[], mirrorRoot: string = MIRROR_ROOT): OrphanMirror[] {
  let dirents;
  try {
    dirents = readdirSync(mirrorRoot, { withFileTypes: true });
  } catch {
    return [];
  }
  const live = new Set(entries.map((entry) => entry.mirrorName));
  const orphans: OrphanMirror[] = [];
  for (const entry of dirents) {
    if (!entry.name.startsWith(MIRROR_PREFIX)) continue;
    if (live.has(entry.name)) continue;
    if (!entry.isDirectory()) {
      orphans.push({
        name: entry.name,
        generated: false,
        reason: 'not a directory (a symlink or a stray file), so it is reported rather than removed',
      });
      continue;
    }
    let body = '';
    try {
      body = readFileSync(join(mirrorRoot, entry.name, 'SKILL.md'), 'utf8');
    } catch {
      orphans.push({
        name: entry.name,
        generated: false,
        reason: 'no readable SKILL.md, so there is no evidence this command created it',
      });
      continue;
    }
    // Anchored to the generated body's OWN opening lines, not merely `includes`. A
    // hand-written `cutdown-*` skill that QUOTES the banner (documentation about the
    // mirror format, say) would otherwise be classified generated and pruned.
    // Newline-normalised first: with `core.autocrlf=true` and no `.gitattributes` the
    // anchor is `---\r\nname: ` on a fresh clone, so a raw `startsWith` classified
    // EVERY generated mirror as hand-written — `--prune` would then never remove a
    // real orphan and would report all ten as golden-rule-3 problems.
    const normalised = normaliseNewlines(body);
    const generated =
      normalised.startsWith(`---${'\n'}name: `) &&
      normalised.includes(`<!-- ${GENERATED_BANNER}. Edit cutdown/skills/`);
    orphans.push({
      name: entry.name,
      generated,
      reason: generated
        ? 'generated by this command and its source skill no longer exists'
        : `its SKILL.md does not carry the generated banner, so it was NOT written by \`cutdown skills sync\` — reported, never removed (golden rule 3)`,
    });
  }
  return orphans.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

/** `cutdown skills sync [--check]` — the CLI surface. */
export function skillsSyncCommand(check: boolean, prune = false): number {
  const outcome = skillsSync({ check, prune });

  for (const warning of outcome.warnings) {
    process.stderr.write(`skills sync WARNING — ${warning.skill}: ${warning.problem}\n`);
  }

  if (outcome.problems.length > 0) {
    for (const problem of outcome.problems) {
      process.stderr.write(`skills sync FAIL — ${problem.skill}: ${problem.problem}\n`);
    }
    process.stderr.write(
      `\nskills sync — ${String(outcome.problems.length)} problem(s); NOTHING was written. ` +
        `The registry and mirror are generated together or not at all (a half-written registry would describe a skill set that does not exist).\n`,
    );
    return 1;
  }

  if (check) {
    process.stdout.write(`skills sync --check — registry and mirror are current for ${String(outcome.skillCount)} skill(s): PASS\n`);
    return 0;
  }

  for (const file of outcome.written) process.stdout.write(`  wrote   ${file}\n`);
  for (const file of outcome.removed) process.stdout.write(`  removed ${file}\n`);
  process.stdout.write(
    outcome.written.length === 0 && outcome.removed.length === 0
      ? `skills sync — ${String(outcome.skillCount)} skill(s), no changes (idempotent).\n`
      : `skills sync — ${String(outcome.skillCount)} skill(s); ${String(outcome.written.length)} file(s) written, ${String(outcome.removed.length)} removed.\n`,
  );
  return 0;
}
