// Persona 3 - editor seat (invited collaborator). Depends on studio-operator
// having run first (it provisions this identity and its editor membership -
// see e2e/support/db-shortcut.ts - and records whether Profile A's voice
// brain is active). Confirms an editor CAN generate and log results, and
// CANNOT reach owner-only billing/workspace controls - the boundary is
// asserted, not skipped.
//
// THE STUDIO CHAPTER READS THE OPERATOR'S OUTCOME (creator-ready Phase 2,
// invariant `operator-refusal-recorded-not-silent`): with `operatorVoice:
// "active"` a press must end usable or honestly refused and `studio-blocked`
// is a FAILURE; with `"refused"` the precondition refusal is asserted
// explicitly. A handoff without the field fails - never a silent default.
import { test, expect } from "@playwright/test";
import { journeyArtifacts } from "../support/artifacts";
import { signIn, signOut } from "../support/auth";
import { waitForGenerationOutcome } from "../support/generation";
import { readHandoff } from "../support/handoff";
import { MAIN_CHAPTERS } from "../support/main-chapters";

const artifacts = journeyArtifacts("editor-seat");

test.setTimeout(6 * 60 * 1000);

type EditorHandoff = {
  email: string;
  password: string;
  ownerEmail: string;
  operatorVoice?: unknown;
};

test("editor seat - generate and log, but no billing control", async ({ page }) => {
  artifacts.attach(page);

  let handoff: EditorHandoff;
  try {
    handoff = readHandoff<EditorHandoff>("editor-seat");
  } catch (err) {
    test.skip(
      true,
      `No editor handoff found - run studio-operator.spec.ts first (it provisions this identity). ${String(err)}`
    );
    return;
  }
  const operatorVoice = handoff.operatorVoice;
  if (operatorVoice !== "active" && operatorVoice !== "refused") {
    throw new Error(
      `editor handoff has no usable operatorVoice field (got ${JSON.stringify(operatorVoice)}) - studio-operator must record "active" or "refused"; a missing field is never defaulted`
    );
  }
  artifacts.note(`operatorVoice from the studio-operator handoff: ${operatorVoice}`);

  // Chapter 1 - sign in as the provisioned editor.
  await signIn(page, handoff);
  await expect(page.getByRole("button", { name: /sign out/i })).toBeVisible();
  await artifacts.screenshot(page, "signed-in-editor");

  // Chapter 2 - confirm the workspace context: the owner's, not a fresh one.
  // Profile selection is PER-MEMBERSHIP (membership_profile_selections), so
  // the owner having switched to "Profile A" earlier does not carry over to
  // this editor's own membership - selecting it here is not a workaround,
  // it is what a real second seat has to do on first arrival.
  await page.goto("/onboarding");
  await expect(page.getByText("Creator profile").first()).toBeVisible();
  await artifacts.screenshot(page, "onboarding-editor-view");
  const profilePicker = page.getByLabel("Creator profile");
  if (await profilePicker.isVisible().catch(() => false)) {
    const options = await profilePicker.locator("option").allTextContents();
    if (options.some((o) => o.includes("Profile A"))) {
      await profilePicker.selectOption({ label: "Profile A" });
      await page.getByRole("button", { name: "Switch profile" }).click();
      await expect(page.getByRole("heading", { name: "Profile A" })).toBeVisible({ timeout: 15_000 });
      artifacts.note("Editor selected Profile A (per-membership selection, not shared with the owner).");
      await artifacts.screenshot(page, "onboarding-editor-profile-selected");
    }
  }

  // Chapter 3 - an editor CAN generate. Which Studio state is correct depends
  // on what the operator's included voice build did (handoff above).
  await page.goto("/studio");
  const blockedNode = page.getByTestId("studio-blocked");
  if (operatorVoice === "active") {
    // The operator built AND activated Profile A's voice brain: a precondition
    // refusal here would be a real defect, never something to record past.
    await expect(page.getByTestId("studio-no-profile")).toHaveCount(0);
    await expect(blockedNode).toHaveCount(0);
    await page.getByLabel("What do you want to make?").selectOption({ label: "Hooks" });
    await page.locator("#studio-input").fill("A hook, generated by the editor seat e2e journey.");
    await page.getByRole("button", { name: "Make a draft" }).click();
    await page.getByTestId("studio-status").filter({ hasText: /.+/ }).waitFor({ state: "visible", timeout: 15_000 });
    const outcome = await waitForGenerationOutcome(page, 90_000);
    artifacts.note(`editor generation outcome: ${outcome}`);
    expect(
      ["usable", "honest_refusal"],
      "with an active operator voice brain the editor's press must end usable or honestly refused"
    ).toContain(outcome);
  } else {
    // The operator's build was refused by the model (recorded, not retried):
    // the editor sees the precondition refusal, and its reason must never be
    // the role/viewer refusal, which is the one thing an editor must never see.
    await expect(blockedNode).toBeVisible();
    const reason = (await blockedNode.textContent()) ?? "";
    expect(reason, "an editor must never be blocked from Studio by a viewer-role reason").not.toMatch(
      /viewer access/i
    );
    artifacts.note(
      `Studio press not exercised for the editor: precondition refusal after the operator's refused voice build - ${reason}`
    );
  }
  // THE MAIN CHAPTER for this persona, on the shared path both branches reach.
  await expect(
    page
      .locator('[data-testid="studio-blocked"], [data-testid="studio-result"], [data-testid="studio-honest-refusal"]')
      .first()
  ).toBeVisible();
  await artifacts.screenshot(page, MAIN_CHAPTERS["editor-seat"]);

  // Chapter 4 - an editor CAN log a result, when the workspace has a declared
  // metric to log against.
  await page.goto("/results");
  const noMetric = await page.getByTestId("results-no-declared-metric").isVisible().catch(() => false);
  const logBlocked = await page.getByTestId("results-log-blocked").isVisible().catch(() => false);
  artifacts.note(`results: no declared metric=${noMetric}, log blocked for editor=${logBlocked}`);
  // R2/REQ-A02: an editor role must never be the reason logging is withheld.
  expect(logBlocked, "an editor must be able to log a result - only role=viewer or a pause may block it").toBe(false);
  await expect(
    page
      .locator('[data-testid="results-no-declared-metric"], [data-testid="results-log-blocked"], #results-generation')
      .first()
  ).toBeVisible();
  await artifacts.screenshot(page, "results-editor-view");

  // Chapter 5 - the boundary: an editor CANNOT reach owner-only billing
  // controls. The page renders (results history etc. are readable by
  // everyone), but every money-moving control is disabled with a named
  // "not owner" reason. `buy-pack` renders in BOTH subscription branches and
  // puts the not-owner reason first, so it is the one control the reason is
  // asserted inside - unconditionally: the control absent (a failed config
  // read renders <Blocked> instead) fails this chapter rather than skipping it.
  await page.goto("/settings/billing");
  const buyPack = page.getByTestId("buy-pack");
  await expect(buyPack).toBeVisible();
  await expect(buyPack.getByText("Only the workspace owner can change billing")).toBeVisible();
  await artifacts.screenshot(page, "billing-editor-view");
  const subscribeButtons = page.locator('[data-testid^="subscribe-"] button, [data-testid="buy-pack"] button');
  const count = await subscribeButtons.count();
  expect(count, "billing should still render subscribe/pack controls for a non-owner, just disabled").toBeGreaterThan(0);
  for (let i = 0; i < count; i += 1) {
    await expect(subscribeButtons.nth(i)).toBeDisabled();
  }
  const portalButton = page.getByTestId("portal-manage").getByRole("button");
  if (await portalButton.count()) {
    await expect(portalButton).toBeDisabled();
  }
  // The pause form renders only for an OWNER with a live subscription; for an
  // editor its presence would be a role-boundary breach, asserted, never noted.
  await expect(page.getByTestId("pause-form")).toHaveCount(0);
  await expect(buyPack.getByRole("button")).toBeDisabled();
  await artifacts.screenshot(page, "billing-editor-controls-disabled");

  // Chapter 6 - sign out.
  await page.goto("/studio");
  await signOut(page);
  await expect(page.getByRole("link", { name: "Start free, no card" }).first()).toBeVisible();
  await artifacts.screenshot(page, "signed-out");
});
