// Persona 3 - editor seat (invited collaborator). Depends on studio-operator
// having run first (it provisions this identity and its editor membership -
// see e2e/support/db-shortcut.ts). Confirms an editor CAN generate and log
// results, and CANNOT reach owner-only billing/workspace controls - the
// boundary is asserted, not skipped.
import { test, expect } from "@playwright/test";
import { journeyArtifacts } from "../support/artifacts";
import { signIn, signOut } from "../support/auth";
import { readHandoff } from "../support/handoff";
import { waitForGenerationOutcome } from "../support/generation";

const artifacts = journeyArtifacts("editor-seat");

test.setTimeout(6 * 60 * 1000);

type EditorHandoff = { email: string; password: string; ownerEmail: string };

test("editor seat - generate and log, but no billing control", async ({ page }) => {
  artifacts.attach(page);

  let handoff: EditorHandoff;
  try {
    handoff = readHandoff<EditorHandoff>("editor-seat");
  } catch (err) {
    test.skip(
      true,
      `No editor handoff found - run studio-operator.spec.ts first (it provisions this identity). ${String(err)}`
    );
    return;
  }

  // Chapter 1 - sign in as the provisioned editor.
  await signIn(page, handoff);
  await artifacts.screenshot(page, "signed-in-editor");

  // Chapter 2 - confirm the workspace context: the owner's, not a fresh one.
  // Profile selection is PER-MEMBERSHIP (membership_profile_selections), so
  // the owner having switched to "Profile A" earlier does not carry over to
  // this editor's own membership - selecting it here is not a workaround,
  // it is what a real second seat has to do on first arrival.
  await page.goto("/onboarding");
  await artifacts.screenshot(page, "onboarding-editor-view");
  const profilePicker = page.getByLabel("Creator profile");
  if (await profilePicker.isVisible().catch(() => false)) {
    const options = await profilePicker.locator("option").allTextContents();
    if (options.some((o) => o.includes("Profile A"))) {
      await profilePicker.selectOption({ label: "Profile A" });
      await page.getByRole("button", { name: "Switch profile" }).click();
      await expect(page.getByRole("heading", { name: "Profile A" })).toBeVisible({ timeout: 15_000 });
      artifacts.note("Editor selected Profile A (per-membership selection, not shared with the owner).");
      await artifacts.screenshot(page, "onboarding-editor-profile-selected");
    }
  }

  // Chapter 3 - an editor CAN generate. studio-operator's own journey never
  // built or activated a brain for "Profile A" (it is a seats/tiers journey,
  // not a brain-building one), so a real press here is expected to be
  // withheld on a PRECONDITION (no activated brain) - the assertion that
  // matters for THIS persona is that the reason is never the role/viewer
  // refusal, which is the one thing an editor must never see.
  await page.goto("/studio");
  const noProfile = await page.getByTestId("studio-no-profile").isVisible().catch(() => false);
  const blockedNode = page.getByTestId("studio-blocked");
  const blocked = await blockedNode.isVisible().catch(() => false);
  if (!noProfile && !blocked) {
    await page.getByLabel("What do you want to make?").selectOption({ label: "Hooks" });
    await page.locator("#studio-input").fill("A hook, generated by the editor seat e2e journey.");
    await page.getByRole("button", { name: "Make a draft" }).click();
    const outcome = await waitForGenerationOutcome(page, 90_000);
    artifacts.note(`editor generation outcome: ${outcome}`);
    await artifacts.screenshot(page, "studio-editor-generated");
  } else {
    const reason = noProfile ? "no creator profile selected" : await blockedNode.textContent();
    expect(reason ?? "", "an editor must never be blocked from Studio by a viewer-role reason").not.toMatch(
      /viewer access/i
    );
    artifacts.note(`Studio generation not exercised for the editor: ${reason} (workspace precondition, not a role gate)`);
    await artifacts.screenshot(page, "studio-editor-no-generation");
  }

  // Chapter 4 - an editor CAN log a result, when the workspace has a declared
  // metric to log against.
  await page.goto("/results");
  const noMetric = await page.getByTestId("results-no-declared-metric").isVisible().catch(() => false);
  const logBlocked = await page.getByTestId("results-log-blocked").isVisible().catch(() => false);
  artifacts.note(`results: no declared metric=${noMetric}, log blocked for editor=${logBlocked}`);
  await artifacts.screenshot(page, "results-editor-view");
  // R2/REQ-A02: an editor role must never be the reason logging is withheld.
  expect(logBlocked, "an editor must be able to log a result - only role=viewer or a pause may block it").toBe(false);

  // Chapter 5 - the boundary: an editor CANNOT reach owner-only billing
  // controls. The page renders (results history etc. are readable by
  // everyone), but every money-moving control is disabled with a named
  // "not owner" reason.
  await page.goto("/settings/billing");
  await artifacts.screenshot(page, "billing-editor-view");
  const subscribeButtons = page.locator('[data-testid^="subscribe-"] button, [data-testid="buy-pack"] button');
  const count = await subscribeButtons.count();
  expect(count, "billing should still render subscribe/pack controls for a non-owner, just disabled").toBeGreaterThan(0);
  for (let i = 0; i < count; i += 1) {
    await expect(subscribeButtons.nth(i)).toBeDisabled();
  }
  const portalButton = page.getByTestId("portal-manage").getByRole("button");
  if (await portalButton.count()) {
    await expect(portalButton).toBeDisabled();
  }
  const pauseForm = page.getByTestId("pause-form");
  if (await pauseForm.count()) {
    await expect(pauseForm.getByRole("button")).toBeDisabled().catch(() => {
      artifacts.note("pause control shape did not match the expected disabled-button pattern - see screenshot");
    });
  }
  await artifacts.screenshot(page, "billing-editor-controls-disabled");

  // Chapter 6 - sign out.
  await page.goto("/studio");
  await signOut(page);
  await artifacts.screenshot(page, "signed-out");
});
