'use strict';

// Explicit, single-writer CLI. Never dispatches a process, reviewer, hook or network request.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const E = require('../lib/workflow-evidence.js');
const uuid = () => crypto.randomUUID();
const now = () => new Date().toISOString();
const clone = value => JSON.parse(JSON.stringify(value));
const same = (a, b) => E.canonical(a) === E.canonical(b);
const sorted = values => values.slice().sort();

function immutable(request, state, value, extension = 'json') {
  const loc = E.location(request); const rel = 'evidence/' + uuid() + '.' + extension;
  const bytes = extension === 'json' ? Buffer.from(JSON.stringify(value, null, 2) + '\n') : Buffer.from(value);
  if (bytes.length > E.LIMITS.jsonBytes) E.fail('RESOURCE', 'Immutable evidence exceeds 2 MiB.');
  const directory = E.safePath(loc.root, loc.goalDirectory + '/evidence'); fs.mkdirSync(directory, { recursive: true });
  const file = E.safePath(loc.root, loc.goalDirectory + '/' + rel);
  const fd = fs.openSync(file, 'wx'); try { fs.writeFileSync(fd, bytes); fs.fsyncSync(fd); } finally { fs.closeSync(fd); }
  const reference = { path: rel, hash: E.hash(bytes) }; state.resources.push(reference); return reference;
}
function atomicSnapshot(loc, state) {
  const bytes = Buffer.from(JSON.stringify(state, null, 2) + '\n');
  if (bytes.length > E.LIMITS.jsonBytes) E.fail('RESOURCE', 'Workflow snapshot exceeds 2 MiB; inspect its scope before continuing.');
  const temporary = E.safePath(loc.root, loc.goalDirectory + '/workflow-' + uuid() + '.tmp');
  const fd = fs.openSync(temporary, 'wx'); try { fs.writeFileSync(fd, bytes); fs.fsyncSync(fd); } finally { fs.closeSync(fd); }
  E.safePath(loc.root, loc.goalDirectory + '/workflow.json'); fs.renameSync(temporary, loc.snapshot);
}
function response(request, state, ids = {}, ownedLockToken) {
  const options = { ...request, state }; let fingerprint = null;
  try { fingerprint = E.fingerprintInputs(options); } catch { /* Readiness explains unavailable proof. */ }
  let attemptAssessment;
  if (Object.hasOwn(request, 'attemptId')) {
    E.id(request.attemptId, 'attemptId'); const attempt = state.attempts.find(a => a.attemptId === request.attemptId);
    if (!attempt) E.fail('BINDING', 'Unknown attemptId for this workflow.', 'Read the retained attempt IDs from this goal before requesting its assessment inputs.');
    let currentFingerprint = null;
    try { currentFingerprint = E.assessmentFingerprint(options, attempt.obligationIds).digest; } catch { /* Preserve the attempt; readiness explains unavailable inputs. */ }
    attemptAssessment = { attemptId: attempt.attemptId, preFingerprint: attempt.fingerprint.digest, currentFingerprint, currentMatchesReserved: currentFingerprint === attempt.fingerprint.digest, status: attempt.status };
  }
  return { ok: true, stateRevision: state.stateRevision, ids, state, fingerprint, ...(attemptAssessment ? { attemptAssessment } : {}), ...E.deriveReadiness(options, ownedLockToken) };
}
function obligation(raw, state) {
  E.object(raw, 'obligation'); if (raw.obligationId) E.fail('IDENTITY', 'New obligation IDs are generated by the helper.');
  const ob = { ...clone(raw), obligationId: uuid() };
  E.string(ob.key, 'obligation key'); E.oneOf(ob.kind, E.KINDS, 'obligation kind');
  E.strings(ob.coverage, 'obligation coverage').forEach(x => { if (!state.acceptanceScope.includes(x)) E.fail('SCOPE', 'Obligation coverage is outside accepted scope.'); });
  if (ob.roots) {
    E.strings(ob.roots, 'obligation roots').forEach(root => { E.relative(root, true); if (!state.scope.roots.some(base => base === '.' || root === base || root.startsWith(base + '/'))) E.fail('SCOPE', 'Obligation roots must stay within declared scope.'); });
    E.string(ob.dependencyJustification, 'dependencyJustification');
  }
  return ob;
}
function initialize(request, loc) {
  if (fs.existsSync(loc.snapshot)) E.fail('EXISTS', 'This goal already has a workflow; do not replace it.', 'Read status and use an expected-revision amendment.');
  if (request.expectedRevision !== 0) E.fail('REVISION', 'Initialization requires expectedRevision 0 and an absent workflow.');
  E.string(request.title, 'title'); E.oneOf(request.lane, ['fast', 'planned'], 'lane'); E.strings(request.acceptanceScope, 'acceptanceScope');
  E.object(request.authorization, 'authorization'); E.object(request.owner, 'owner'); E.object(request.execution, 'execution'); E.object(request.scope, 'scope');
  const legacy = fs.readdirSync(loc.goal).some(name => /\.md$/i.test(name));
  if (request.legacyInspection) E.string(request.legacyInspection.reference, 'legacy inspection reference');
  const state = { schemaVersion: 1, stateRevision: 1, goalId: uuid(), title: request.title, lane: request.lane, originalAcceptanceScope: clone(request.acceptanceScope), acceptanceScope: clone(request.acceptanceScope), authorization: clone(request.authorization), owners: [{ ...clone(request.owner), since: now(), previousOwnerId: null }], currentOwnerId: request.owner.ownerId, execution: clone(request.execution), scope: clone(request.scope), phases: [], attempts: [], receipts: [], resources: [], findings: [], amendments: [], contractHistory: [], stopGuard: { enabled: false }, nextAction: request.nextAction, createdAt: now(), legacyInspection: request.legacyInspection || null };
  if (state.execution.disposition === 'complete') E.fail('DISPOSITION', 'Initialization cannot claim completed work.');
  const ids = { goalId: state.goalId, phases: {}, gates: {}, obligations: {} };
  for (const p of E.list(request.phases, 'phases', true)) {
    const phase = { phaseId: uuid(), key: p.key, title: p.title, disposition: 'open', gates: [] }; ids.phases[p.key] = phase.phaseId;
    for (const g of E.list(p.gates, 'gates', true)) {
      const budget = g.budget ? clone(g.budget) : { history: 'unknown', consumedBatches: [], reference: null };
      if (budget.extensions?.length) E.fail('BUDGET', 'Initialize base history only; record explicit additional approval through a scoped budget-extension amendment.');
      budget.extensions = [];
      if (legacy && !request.legacyInspection) { budget.history = 'unknown'; budget.reference = null; }
      const gate = { gateId: uuid(), key: g.key, title: g.title || g.key, budget, obligations: [], batches: [] }; ids.gates[g.key] = gate.gateId;
      for (const raw of E.list(g.obligations, 'obligations', true)) { const ob = obligation(raw, state); gate.obligations.push(ob); ids.obligations[ob.key] = ob.obligationId; }
      phase.gates.push(gate);
    }
    state.phases.push(phase);
  }
  const captured = E.captureContract(request, request.contract);
  const contract = { schemaVersion: 1, goalId: state.goalId, contractId: uuid(), revision: 1, previousContract: null, reason: 'Accepted initial contract', acceptanceScope: state.acceptanceScope, ...captured };
  // Validate before writing an immutable object (using a provisional registered reference).
  const provisional = { path: 'evidence/' + uuid() + '.json', hash: '0'.repeat(64) }; state.contract = provisional; state.contractHistory.push(provisional); state.resources.push(provisional); E.validateWorkflow(state); state.resources.pop(); state.contractHistory.pop();
  state.contract = immutable(request, state, contract); state.contractHistory.push(state.contract);
  E.fingerprintInputs({ ...request, state }); return { state, ids };
}
function requireRunning(state, kind) {
  if (state.execution.disposition !== 'running') E.fail('DISPOSITION', 'This goal is not running; preserve its explicit pause or waiting state.');
  const scope = kind === 'review' ? 'reviews' : 'checks';
  if (!state.authorization.scope.includes(scope)) E.fail('AUTHORIZATION', 'Recorded authorization does not cover ' + scope + '.', 'Obtain the missing authorization without changing existing scope.');
}
function gateObligations(gate, ids) {
  E.strings(ids, 'obligationIds'); const obligations = ids.map(id => gate.obligations.find(o => o.obligationId === id));
  if (obligations.some(o => !o)) E.fail('BINDING', 'Coverage names an obligation outside this gate.'); return obligations;
}
function enterPhase(state, phaseId, reference) {
  const phase = state.phases.find(p => p.phaseId === phaseId); if (!phase) E.fail('BINDING', 'Unknown receiving phase.');
  if (state.execution.disposition !== 'running' || !state.authorization.scope.includes('build')) E.fail('AUTHORIZATION', 'Phase entry requires running disposition and retained build authorization.', 'Preserve the pause/wait and obtain or resume the actual authorization before entering this phase.');
  E.string(reference, 'phase entry reference');
  if (phase.enteredRevision == null) { phase.enteredRevision = state.stateRevision + 1; phase.entryReference = reference; }
  const activatedFindingIds = [];
  for (const finding of state.findings.filter(f => f.disposition === 'deferred' && f.deferral?.receivingPhaseId === phaseId)) {
    finding.version++; finding.disposition = 'open'; finding.proofReceiptIds = []; finding.repair = null; finding.applicability = null;
    finding.deferral.activatedRevision = state.stateRevision + 1;
    finding.history.push({ at: now(), version: finding.version, activated: true, reopened: false, disposition: 'open', ownerId: finding.ownerId, reason: 'Named receiving phase entered: ' + reference, receivingPhaseId: phaseId, risk: clone(finding.risk), deferral: clone(finding.deferral), proofReceiptIds: [] });
    activatedFindingIds.push(finding.findingId);
  }
  return activatedFindingIds;
}
function reserve(request, state) {
  const { gate, phase } = E.findGate(state, request.gateId); E.oneOf(request.mode, ['batch', 'run', 'unavailable'], 'reservation mode');
  if (request.mode === 'unavailable') {
    // Retiring a slot edits the retained review schedule, so it needs the same running/authorization
    // envelope as the other two modes; a paused, blocked or completed goal must not be reshaped.
    requireRunning(state, 'review');
    E.string(request.reason, 'unavailable slot reason'); const slot = gate.batches.flatMap(b => b.slots).find(s => s.slotId === request.slotId);
    if (!slot) E.fail('BINDING', 'Unknown reserved slot.');
    if (slot.unavailable || state.attempts.some(a => a.slotId === slot.slotId)) E.fail('BUDGET', 'Only an unused reserved slot can be retired; actual attempts need terminal evidence.');
    slot.unavailable = { at: now(), reason: request.reason, actualDispatch: false };
    return { slotId: slot.slotId };
  }
  if (request.mode === 'batch') {
    requireRunning(state, 'review');
    if (gate.budget.history !== 'known') E.fail('UNKNOWN_BUDGET', 'Review history is unknown; no evaluation may start.', 'Inspect retained history or obtain a history confirmation, then amend the budget without erasing attempts.');
    E.integer(request.batch, 'batch');
    const next = gate.budget.consumedBatches.length ? Math.max(...gate.budget.consumedBatches) + 1 : 0;
    if (!E.reviewBatches(gate).includes(next)) E.fail('BUDGET', 'The retained review allowance is consumed.', 'Report the residual and obtain explicit gate-scoped approval, then record a bounded budget-extension amendment before another evaluation.');
    if (request.batch !== next) E.fail('BUDGET', 'The requested batch is not the next retained allowance.');
    if (gate.batches.some(b => b.slots.some(s => !s.unavailable && !state.attempts.some(a => a.slotId === s.slotId && a.status !== 'pending')))) E.fail('PENDING', 'A previous reserved batch still has unused or pending slots.', 'Finish or explicitly record unavailable/interrupted results for the reserved slots; do not erase them.');
    const readiness = E.deriveReadiness({ ...request, state });
    const satisfied = new Set(readiness.coveredObligationIds);
    const required = gate.obligations.filter(o => E.isReview(o) && !satisfied.has(o.obligationId)).map(o => o.obligationId);
    const batch = { batchId: uuid(), number: request.batch, fingerprint: E.fingerprintInputs({ ...request, state }), reservedAt: now(), slots: [] };
    const slots = E.list(request.slots, 'complete batch slots', true); E.unique(slots.map(s => s.key), 'slot keys');
    const keys = new Set(slots.map(s => s.key));
    for (const slot of slots) {
      E.string(slot.key, 'slot key'); const obs = gateObligations(gate, slot.obligationIds);
      if (obs.some(o => !E.isReview(o))) E.fail('BINDING', 'Batch slots are only for reviewer obligations.');
      if (obs.some(o => o.final || o.separate) && obs.length !== 1) E.fail('INDEPENDENCE', 'Final and full-gate reviewer obligations need separate slots.');
      const after = slot.after || []; E.strings(after, 'slot dependencies', false);
      if (after.some(key => !keys.has(key) || key === slot.key)) E.fail('BINDING', 'Slot dependencies must name other slots in this batch.');
      if (obs.some(o => o.final) && slots.some(s => s.key !== slot.key && !after.includes(s.key))) E.fail('BINDING', 'The final generalist must depend on every specialist slot.');
      batch.slots.push({ slotId: uuid(), key: slot.key, obligationIds: sorted(slot.obligationIds), role: slot.role || obs[0].role || 'independent-reviewer', after: sorted(after) });
    }
    const coverage = batch.slots.flatMap(s => s.obligationIds); E.unique(coverage, 'batch coverage');
    if (request.batch > 2) {
      const extension = gate.budget.extensions.find(x => x.batches.includes(request.batch));
      if (coverage.some(obId => !extension.approval.obligationIds.includes(obId))) E.fail('BUDGET', 'This extended batch exceeds the explicitly approved obligation scope.');
      batch.extensionId = extension.extensionId;
    }
    if (required.some(id => !coverage.includes(id))) E.fail('OBLIGATION', 'The complete batch must reserve every currently owed reviewer, including the final generalist.');
    E.validateSlotGraph(batch.slots); enterPhase(state, phase.phaseId, 'Successful assessment reservation in phase ' + phase.key); gate.batches.push(batch); gate.budget.consumedBatches.push(request.batch);
    return { batchId: batch.batchId, slots: Object.fromEntries(batch.slots.map(s => [s.key, s.slotId])) };
  }
  let obligationIds, slotId = null, batchNumber = null;
  if (request.slotId) {
    requireRunning(state, 'review'); if (gate.budget.history !== 'known') E.fail('UNKNOWN_BUDGET', 'Review history remains unknown.');
    const batch = gate.batches.find(b => b.slots.some(s => s.slotId === request.slotId)); if (!batch) E.fail('BINDING', 'Unknown reserved slot.');
    const slot = batch.slots.find(s => s.slotId === request.slotId);
    if (slot.unavailable) E.fail('BUDGET', 'This reserved slot was retired without dispatch; it cannot be reused.');
    if (state.attempts.some(a => a.slotId === slot.slotId)) E.fail('BUDGET', 'This slot already reserved its actual evaluation; a continued verdict needs a retry slot.');
    if (batch.fingerprint.digest !== E.fingerprintInputs({ ...request, state }).digest) E.fail('STALE', 'The batch inputs changed; a reserved final slot cannot review changed work for free.', 'Record the interrupted/unavailable original slots, then use only the remaining retry allowance.');
    for (const key of slot.after) { const prerequisite = batch.slots.find(s => s.key === key); if (!state.attempts.some(a => a.slotId === prerequisite.slotId && a.status !== 'pending')) E.fail('PENDING', 'A required earlier reviewer has not returned.'); }
    obligationIds = slot.obligationIds; slotId = slot.slotId; batchNumber = batch.number;
  } else {
    obligationIds = sorted(E.strings(request.obligationIds, 'obligationIds')); const obs = gateObligations(gate, obligationIds);
    if (obs.some(E.isReview)) E.fail('BUDGET', 'Reviewer evaluations require a previously saved complete batch and slot.');
    requireRunning(state, 'check');
    const commands = [...new Set(obs.filter(o => o.kind === 'check').map(o => o.command))]; if (commands.length > 1) E.fail('BINDING', 'Different check commands require distinct attempts.');
  }
  const fingerprint = E.assessmentFingerprint({ ...request, state }, obligationIds);
  enterPhase(state, phase.phaseId, 'Successful assessment reservation in phase ' + phase.key);
  const attempt = { attemptId: uuid(), phaseId: phase.phaseId, gateId: gate.gateId, slotId, batch: batchNumber, obligationIds, fingerprint, status: 'pending', findingVersions: E.findingVersions(state, gate.gateId), reservedRevision: state.stateRevision + 1, reservedAt: now(), sessionId: state.execution.sessionId, constructionOwnerId: state.currentOwnerId };
  state.attempts.push(attempt); return { attemptId: attempt.attemptId, preFingerprint: attempt.fingerprint.digest };
}
function timestamp(value, label) { E.string(value, label); if (!Number.isFinite(Date.parse(value))) E.fail('INVALID', label + ' must be an ISO timestamp.'); return value; }
function recordEvidence(request, state) {
  const attempt = state.attempts.find(a => a.attemptId === request.attemptId); if (!attempt) E.fail('BINDING', 'Unknown reserved attempt.');
  if (attempt.status !== 'pending' || state.receipts.some(r => r.attemptId === attempt.attemptId)) E.fail('DUPLICATE', 'An attempt can have one immutable terminal receipt.');
  if (request.goalId !== state.goalId || request.gateId !== attempt.gateId || request.slotId !== attempt.slotId || !same(sorted(E.strings(request.obligationIds, 'obligationIds')), attempt.obligationIds)) E.fail('BINDING', 'Evidence does not match the exact goal, gate, slot and reserved obligation coverage.');
  E.oneOf(request.result, E.RESULTS, 'result'); E.hashString(request.preFingerprint, 'preFingerprint'); E.hashString(request.postFingerprint, 'postFingerprint');
  if (request.preFingerprint !== attempt.fingerprint.digest) E.fail('BINDING', 'Evidence does not match its reserved pre-assessment inputs.');
  const report = E.object(request.report, 'report'); let content;
  if (Object.hasOwn(report, 'content') === Object.hasOwn(report, 'path')) E.fail('INVALID', 'Supply exactly one report content or report path.');
  if (report.path) {
    E.relative(report.path); if (!/^evidence\/[^/]+$/.test(report.path)) E.fail('PATH', 'Report source must be directly beneath this goal evidence directory.');
    const loc = E.location(request); const bytes = E.readBounded(E.safePath(loc.root, loc.goalDirectory + '/' + report.path)); content = bytes.toString('utf8');
    const registered = state.resources.find(r => r.path === report.path);
    if (registered && registered.hash !== E.hash(bytes)) E.fail('RESOURCE', 'An existing immutable report changed.');
    if (!registered) state.resources.push({ path: report.path, hash: E.hash(bytes), importedReport: true });
  } else content = E.string(report.content, 'report.content');
  const current = E.assessmentFingerprint({ ...request, state }, attempt.obligationIds);
  if (request.postFingerprint !== current.digest || (['PASS', 'FAIL'].includes(request.result) && request.preFingerprint !== request.postFingerprint)) E.fail('STALE', 'Inputs changed during the assessment; it cannot establish a verdict.', 'Retain the attempt and report unverified/interrupted evidence before any allowed retry.');
  const observed = E.object(request.observed, 'observed');
  const { gate } = E.findGate(state, attempt.gateId); const obs = gateObligations(gate, attempt.obligationIds);
  E.validateExecutionEvidence(request, attempt, state, obs);
  const oldReceipts = state.receipts.map(r => E.receiptData(request, state, r));
  if (observed.dispatchId !== null && oldReceipts.some(r => r.observed.dispatchId === observed.dispatchId && (r.observed.sessionId === null || observed.sessionId === null || r.observed.sessionId === observed.sessionId))) E.fail('DUPLICATE', 'This observed dispatch already has a receipt; it cannot be replayed into another slot.');
  timestamp(request.startedAt, 'startedAt'); timestamp(request.finishedAt, 'finishedAt'); if (Date.parse(request.finishedAt) < Date.parse(request.startedAt)) E.fail('INVALID', 'Evidence timestamps are reversed.');
  const reportRef = immutable(request, state, content, 'txt');
  const receipt = { schemaVersion: 1, receiptId: uuid(), goalId: state.goalId, phaseId: attempt.phaseId, gateId: attempt.gateId, slotId: attempt.slotId, attemptId: attempt.attemptId, reservedRevision: attempt.reservedRevision, recordedRevision: state.stateRevision + 1, findingVersions: clone(attempt.findingVersions), obligationIds: attempt.obligationIds, preFingerprint: request.preFingerprint, postFingerprint: request.postFingerprint, result: request.result, report: reportRef, observed: clone(observed), reconciliation: request.reconciliation ? clone(request.reconciliation) : null, command: request.command || null, exitCode: request.exitCode ?? null, rawVerdict: request.rawVerdict || null, requested: request.requested || { model: null, effort: null }, capabilities: request.capabilities || { model: null, effort: null }, startedAt: request.startedAt, finishedAt: request.finishedAt };
  const reference = immutable(request, state, receipt); state.receipts.push({ receiptId: receipt.receiptId, attemptId: attempt.attemptId, recordedRevision: receipt.recordedRevision, ...reference }); attempt.status = request.result; attempt.finishedAt = request.finishedAt;
  return { receiptId: receipt.receiptId };
}
function recordFinding(request, state) {
  if (!request.findingId) {
    E.findGate(state, request.gateId); E.oneOf(request.severity, E.SEVERITIES, 'severity'); E.oneOf(request.classification, ['residual', 'sibling', 'fix-induced', 'disputed'], 'classification'); E.string(request.invariantId, 'invariantId'); E.string(request.description, 'description');
    if (!state.owners.some(o => o.ownerId === request.ownerId)) E.fail('BINDING', 'Finding owner must belong to retained owner lineage.');
    if (request.parentFindingId && !state.findings.some(f => f.findingId === request.parentFindingId && f.invariantId === request.invariantId && f.gateId === request.gateId)) E.fail('BINDING', 'Related findings must retain gate and invariant identity.');
    if (['sibling', 'fix-induced'].includes(request.classification) && !request.parentFindingId) E.fail('BINDING', 'A related finding requires its original parentFindingId.');
    const risk = request.risk ? clone(request.risk) : { security: 'unknown', dataLoss: 'unknown', reference: null }; E.validateRisk(risk);
    const finding = { findingId: uuid(), version: 1, applicability: null, gateId: request.gateId, severity: request.severity, classification: request.classification, invariantId: request.invariantId, description: request.description, parentFindingId: request.parentFindingId || null, ownerId: request.ownerId, disposition: 'open', risk, deferral: null, repair: request.repair || null, proofReceiptIds: [], history: [{ at: now(), version: 1, disposition: 'open', ownerId: request.ownerId, reason: 'Recorded finding', risk: clone(risk) }] };
    state.findings.push(finding); return { findingId: finding.findingId };
  }
  const finding = state.findings.find(f => f.findingId === request.findingId); if (!finding) E.fail('BINDING', 'Unknown findingId.'); E.string(request.reason, 'finding update reason');
  for (const key of ['gateId', 'severity', 'classification', 'invariantId', 'parentFindingId']) if (Object.hasOwn(request, key) && request[key] !== finding[key]) E.fail('IDENTITY', 'Finding identity and original classification cannot be erased.');
  E.oneOf(request.disposition, ['open', 'resolved', 'accepted-risk', 'deferred', 'disputed'], 'disposition');
  if (request.risk) { E.validateRisk(request.risk); for (const key of ['security', 'dataLoss']) if (finding.risk?.[key] === 'yes' && request.risk[key] !== 'yes') E.fail('FINDING', 'Positive recorded risk cannot be downgraded.'); finding.risk = clone(request.risk); }
  if (request.disposition === 'deferred') {
    const deferral = clone(E.object(request.deferral, 'deferral'));
    if (finding.deferral?.activatedRevision != null || finding.history.some(h => h.activated === true)) E.fail('DEFERRAL', 'An activated finding cannot be deferred again.');
    if (finding.deferral && finding.deferral.receivingPhaseId !== deferral.receivingPhaseId) E.fail('IDENTITY', 'The original receiving phase binding cannot be moved.');
    const receiving = state.phases.find(p => p.phaseId === deferral.receivingPhaseId);
    if (!receiving || receiving.enteredRevision != null || receiving.disposition === 'complete' || receiving.gates.some(g => g.batches.length || state.attempts.some(a => a.gateId === g.gateId))) E.fail('DEFERRAL', 'The receiving phase must exist and must not already have entered, reserved work or closed.');
    const proposed = { ...finding, disposition: 'deferred', deferral: { ...deferral, findingVersion: finding.version, recordedRevision: state.stateRevision + 1, activatedRevision: null } };
    E.validateDeferralEvidence({ ...request, state: { ...state, stateRevision: state.stateRevision + 1 } }, proposed);
    finding.deferral = proposed.deferral; finding.risk = clone(deferral.risk); finding.proofReceiptIds = []; finding.repair = null; finding.applicability = null;
  } else if (Object.hasOwn(request, 'deferral')) E.fail('DEFERRAL', 'Deferral metadata is recorded only with the deferred disposition.');
  if (request.ownerId) { if (!state.owners.some(o => o.ownerId === request.ownerId)) E.fail('BINDING', 'Replacement owner is missing from lineage.'); finding.ownerId = request.ownerId; }
  const reopened = request.disposition === 'open' && finding.disposition !== 'open';
  if (reopened) { finding.version++; finding.proofReceiptIds = []; finding.repair = null; finding.applicability = null; }
  if (Object.hasOwn(request, 'applicability')) finding.applicability = clone(request.applicability);
  if (request.repair) finding.repair = clone(request.repair); if (request.proofReceiptIds) finding.proofReceiptIds = clone(request.proofReceiptIds);
  if (request.disposition === 'resolved') E.validateFindingProof({ ...request, state }, finding);
  finding.disposition = request.disposition; finding.history.push({ at: now(), version: finding.version, reopened, applicability: clone(finding.applicability), disposition: finding.disposition, ownerId: finding.ownerId, reason: request.reason, proofReceiptIds: clone(finding.proofReceiptIds), repair: clone(finding.repair), risk: clone(finding.risk || { security: 'unknown', dataLoss: 'unknown', reference: null }), deferral: clone(finding.deferral || null) });
  return { findingId: finding.findingId };
}
function amend(request, state) {
  E.string(request.reason, 'amendment reason'); const change = E.object(request.change, 'change'); const record = { amendmentId: uuid(), at: now(), reason: request.reason, type: change.type, previousRevision: state.stateRevision };
  if (change.type === 'contract') {
    E.strings(change.acceptanceScope, 'acceptanceScope'); if (state.acceptanceScope.some(x => !change.acceptanceScope.includes(x))) E.fail('SCOPE', 'Contract amendments cannot erase original or already accepted scope.');
    const captured = E.captureContract(request, change.contract); const contract = { schemaVersion: 1, goalId: state.goalId, contractId: uuid(), revision: state.contractHistory.length + 1, previousContract: clone(state.contract), reason: request.reason, acceptanceScope: change.acceptanceScope, ...captured };
    record.previousContract = clone(state.contract); state.contract = immutable(request, state, contract); state.contractHistory.push(state.contract); state.acceptanceScope = clone(change.acceptanceScope);
  } else if (change.type === 'execution') {
    const execution = E.object(change.execution, 'execution'); E.string(execution.sessionId, 'sessionId'); E.oneOf(execution.disposition, ['running', 'paused', 'waiting', 'blocked'], 'disposition'); record.previousExecution = clone(state.execution); state.execution = clone(execution);
  } else if (change.type === 'phase-entry') {
    record.phaseId = change.phaseId; record.reference = change.reference; record.activatedFindingIds = enterPhase(state, change.phaseId, change.reference);
  } else if (change.type === 'owner') {
    const owner = E.object(change.owner, 'owner'); E.string(owner.ownerId, 'ownerId'); E.string(owner.contextId, 'contextId');
    if (state.owners.some(o => o.ownerId === owner.ownerId)) E.fail('IDENTITY', 'Owner replacement must append a new lineage member.');
    state.owners.push({ ...clone(owner), since: now(), previousOwnerId: state.currentOwnerId }); record.previousOwnerId = state.currentOwnerId; state.currentOwnerId = owner.ownerId;
  } else if (change.type === 'obligations') {
    const { gate } = E.findGate(state, change.gateId); const added = E.list(change.add, 'new obligations', true).map(raw => obligation(raw, state));
    const keys = new Set(state.phases.flatMap(p => p.gates.flatMap(g => g.obligations.map(o => o.key)))); if (added.some(o => keys.has(o.key))) E.fail('DUPLICATE', 'New obligations cannot replace existing identities.');
    gate.obligations.push(...added); record.gateId = gate.gateId; record.addedObligationIds = added.map(o => o.obligationId);
  } else if (change.type === 'budget') {
    const { gate } = E.findGate(state, change.gateId); E.string(change.reference, 'history confirmation reference'); E.list(change.consumedBatches, 'consumedBatches').forEach(n => E.oneOf(n, E.reviewBatches(gate), 'batch')); E.unique(change.consumedBatches, 'consumed batches');
    if (gate.budget.consumedBatches.some(n => !change.consumedBatches.includes(n))) E.fail('BUDGET', 'An amendment cannot erase consumed review history.');
    if (change.consumedBatches.some(n => n > 2 && !gate.budget.consumedBatches.includes(n))) E.fail('BUDGET', 'An ordinary history amendment cannot consume or launder an additional approved evaluation.');
    record.previousBudget = clone(gate.budget); gate.budget = { ...gate.budget, history: 'known', consumedBatches: sorted(change.consumedBatches), reference: change.reference };
  } else if (change.type === 'budget-extension') {
    const { gate } = E.findGate(state, change.gateId); const allowed = E.reviewBatches(gate);
    if (gate.budget.history !== 'known' || allowed.some(n => !gate.budget.consumedBatches.includes(n))) E.fail('BUDGET', 'Resolve history and exhaust the existing allowance before recording another extension.');
    if (gate.batches.some(b => b.slots.some(s => !s.unavailable && !state.attempts.some(a => a.slotId === s.slotId && a.status !== 'pending')))) E.fail('PENDING', 'Reconcile all unused and pending review slots before extending the gate.');
    E.list(change.batches, 'extension batches', true); E.object(change.approval, 'explicit approval');
    const extension = { extensionId: uuid(), batches: clone(change.batches), approval: clone(change.approval), authorizedAt: now(), authorizedRevision: state.stateRevision + 1 };
    record.gateId = gate.gateId; record.previousBudget = clone(gate.budget); record.extension = clone(extension);
    gate.budget.extensions = [...(gate.budget.extensions || []), extension]; E.reviewBatches(gate);
  } else if (change.type === 'rename') {
    E.string(change.title, 'title'); if (change.gateId) { const { gate } = E.findGate(state, change.gateId); record.previousTitle = gate.title; gate.title = change.title; } else { const phase = state.phases.find(p => p.phaseId === change.phaseId); if (!phase) E.fail('BINDING', 'Unknown phaseId.'); record.previousTitle = phase.title; phase.title = change.title; }
  } else E.fail('INVALID', 'Unsupported amendment; identities and attempt history cannot be replaced.');
  state.amendments.push(record); return { amendmentId: record.amendmentId, ...(record.addedObligationIds ? { obligationIds: record.addedObligationIds } : {}), ...(record.activatedFindingIds ? { activatedFindingIds: record.activatedFindingIds } : {}) };
}
// Records an install/sync's observed target file actions as .claude/pack-installation.json.
// Deliberately goal-independent: it never touches E.location(), the goal lock, expectedRevision,
// attemptId, validateWorkflow or atomicSnapshot (all of which assume a goal-shaped state) — an
// installation receipt has no goal, no phases, no stateRevision. Provenance is optional to a
// successful install; the caller (install.sh/install.ps1/sync-pack) is responsible for containing
// any failure here as a non-fatal note, never as an install failure.
function hashFile(absPath) {
  if (!absPath) return null;
  try { return E.hash(fs.readFileSync(absPath)); }
  catch (error) { E.fail('RESOURCE', 'Cannot read ' + absPath + ' to record its installation action: ' + error.message); }
}
function recordInstall(request) {
  E.object(request, 'request');
  const root = E.project(request.projectRoot);
  E.string(request.generatorMarker, 'generatorMarker'); E.string(request.sourceRelease, 'sourceRelease');
  const selectedModules = E.list(request.selectedModules || [], 'selectedModules').map(m => E.string(m, 'selectedModules entry'));
  // discovered=true: these paths are filesystem-discovered by an installer/sync tree walk, not
  // typed by a person — matches fingerprintInputs' own reasoning for the same flag.
  const submittedActions = E.list(request.actions, 'actions').map(a => {
    E.object(a, 'action'); E.relative(a.path, false, true); E.oneOf(a.action, ['copied', 'skipped-existing', 'settings-sidecar', 'customized-merged', 'missing'], 'action');
    const sourcePath = a.sourcePath != null ? E.string(a.sourcePath, 'action.sourcePath') : null;
    const targetPath = a.targetPath != null ? E.string(a.targetPath, 'action.targetPath') : null;
    return { path: a.path, action: a.action, sourceHash: hashFile(sourcePath), targetHash: hashFile(targetPath) };
  });
  const receiptPath = path.join(root, '.claude', 'pack-installation.json');
  const lockPath = path.join(root, '.claude', 'pack-installation.lock');
  fs.mkdirSync(path.dirname(receiptPath), { recursive: true });
  const token = JSON.stringify({ pid: process.pid, token: uuid(), createdAt: now() }); let lock;
  try { lock = fs.openSync(lockPath, 'wx'); } catch (error) { if (error.code === 'EEXIST') E.fail('LOCKED', 'Another or uncertain writer owns the installation-receipt lock.', 'Inspect the lock owner and recover only after proving it is gone; age alone is insufficient.'); throw error; }
  try {
    fs.writeFileSync(lock, token); fs.fsyncSync(lock);
    // Never overwrite an existing receipt this generator didn't (verifiably) write — preserve it
    // instead. A malformed/unparseable file is exactly as unverifiable as a foreign marker: it
    // gets the same protection, not the benefit of the doubt.
    let prior = null;
    if (fs.existsSync(receiptPath)) {
      try { prior = JSON.parse(fs.readFileSync(receiptPath, 'utf8')); } catch { /* unverifiable; protected below */ }
      if (!prior || prior.generatorMarker !== request.generatorMarker) E.fail('RECEIPT_FOREIGN', 'An existing installation receipt was not written by this generator, or could not be verified; it is preserved unchanged.', 'Inspect .claude/pack-installation.json before installing or syncing again.');
    }
    // Merge by path, submitted actions winning: a partial submission (e.g. /sync-pack recording
    // only what it actually touched) must not erase the comprehensive per-file history an earlier
    // full-tree install recorded for every untouched file. Sorted by path afterward — the two
    // installers walk their source tree in different, platform-native orders (bash `find` vs
    // PowerShell `Get-ChildItem -Recurse`), and a deterministic receipt shouldn't record that
    // difference as if it were meaningful.
    const byPath = new Map((prior && Array.isArray(prior.actions) ? prior.actions : []).map(a => [a.path, a]));
    for (const a of submittedActions) byPath.set(a.path, a);
    const actions = [...byPath.values()].sort((a, b) => a.path < b.path ? -1 : a.path > b.path ? 1 : 0);
    const receipt = { schemaVersion: E.SCHEMA_VERSION, generatorMarker: request.generatorMarker, sourceRelease: request.sourceRelease, at: now(), selectedModules, actions };
    const bytes = Buffer.from(JSON.stringify(receipt, null, 2) + '\n');
    const temporary = path.join(path.dirname(receiptPath), 'pack-installation-' + uuid() + '.tmp');
    const fd = fs.openSync(temporary, 'wx'); try { fs.writeFileSync(fd, bytes); fs.fsyncSync(fd); } finally { fs.closeSync(fd); }
    try { fs.renameSync(temporary, receiptPath); } catch (error) { try { fs.unlinkSync(temporary); } catch { /* best effort */ } throw error; }
    return { ok: true, receiptPath: '.claude/pack-installation.json' };
  } finally {
    fs.closeSync(lock);
    try { if (fs.readFileSync(lockPath, 'utf8') === token) fs.unlinkSync(lockPath); } catch { /* Preserve uncertain ownership. */ }
  }
}
function execute(verb, request) {
  E.oneOf(verb, ['init', 'status', 'reserve-attempt', 'record-evidence', 'record-finding', 'amend', 'close', 'record-install'], 'verb'); E.object(request, 'request');
  if (verb === 'record-install') return recordInstall(request);
  const loc = E.location(request);
  if (verb === 'status') { const loaded = E.loadWorkflow(request); if (loaded.status !== 'valid') E.fail(loaded.error.code, loaded.error.message, loaded.error.nextAction); return response(request, loaded.state); }
  E.integer(request.expectedRevision, 'expectedRevision');
  // Shape-check attemptId BEFORE the lock and the commit. response() also checks it, but response()
  // runs after atomicSnapshot(), so a throw there would commit the mutation and report failure —
  // exactly the divergence between the caller's model and disk that this engine exists to prevent.
  if (Object.hasOwn(request, 'attemptId')) E.id(request.attemptId, 'attemptId');
  if (verb !== 'init' && !fs.existsSync(loc.goal)) E.fail('MISSING', 'Goal has no workflow snapshot; inspect legacy evidence first.');
  fs.mkdirSync(loc.goal, { recursive: true }); E.safePath(loc.root, loc.goalDirectory);
  const token = JSON.stringify({ pid: process.pid, token: uuid(), createdAt: now() }); let lock;
  try { lock = fs.openSync(loc.lock, 'wx'); } catch (error) { if (error.code === 'EEXIST') E.fail('LOCKED', 'Another or uncertain writer owns this goal lock.', 'Inspect the lock owner and recover only after proving it is gone; age alone is insufficient.'); throw error; }
  try {
    fs.writeFileSync(lock, token); fs.fsyncSync(lock); let state, ids;
    if (verb === 'init') ({ state, ids } = initialize(request, loc));
    else {
      const loaded = E.loadWorkflow(request); if (loaded.status !== 'valid') E.fail(loaded.error.code, loaded.error.message, loaded.error.nextAction); state = loaded.state;
      if (state.stateRevision !== request.expectedRevision) E.fail('REVISION', 'Expected revision does not match the current complete snapshot.', 'Read status, reconcile the changes, and retry with its current revision.');
      // Never mutate around a missing or altered immutable resource.
      for (const resource of state.resources) E.resourceData(request, state, resource);
      if (verb === 'reserve-attempt') ids = reserve(request, state);
      else if (verb === 'record-evidence') ids = recordEvidence(request, state);
      else if (verb === 'record-finding') ids = recordFinding(request, state);
      else if (verb === 'amend') ids = amend(request, state);
      else {
        if (request.phaseId) enterPhase(state, request.phaseId, 'Successful scoped closure inspection');
        const readiness = E.deriveReadiness({ ...request, state: { ...state, stateRevision: state.stateRevision + 1 } }, token);
        state.lastClosure = { at: now(), phaseId: request.phaseId || null, ...readiness };
        if (readiness.readiness === 'Ready') { if (request.phaseId) state.phases.find(p => p.phaseId === request.phaseId).disposition = 'complete'; else state.execution.disposition = 'complete'; }
        ids = {};
      }
      state.stateRevision++; state.updatedAt = now();
    }
    // Unknown-attempt binding is also settled before the commit, for the same reason: after
    // atomicSnapshot() the mutation is on disk and reporting it as failed would be untruthful.
    if (Object.hasOwn(request, 'attemptId') && !state.attempts.some(a => a.attemptId === request.attemptId)) E.fail('BINDING', 'Unknown attemptId for this workflow.', 'Read the retained attempt IDs from this goal before requesting its assessment inputs.');
    E.validateWorkflow(state); atomicSnapshot(loc, state);
    const reloaded = E.loadWorkflow(request); if (reloaded.status !== 'valid' || reloaded.state.stateRevision !== state.stateRevision) E.fail('PERSISTENCE', 'Cannot confirm the saved reservation/state; do not dispatch.');
    const out = response(request, reloaded.state, ids, token);
    if (verb === 'reserve-attempt' && ids.attemptId) out.fingerprint = state.attempts.find(a => a.attemptId === ids.attemptId).fingerprint;
    return out;
  } finally {
    fs.closeSync(lock);
    // Remove only the exact lock created by this invocation; never another writer's lock.
    try { if (fs.readFileSync(loc.lock, 'utf8') === token) fs.unlinkSync(loc.lock); } catch { /* Preserve uncertain ownership. */ }
  }
}
async function main() {
  const chunks = []; let size = 0;
  for await (const chunk of process.stdin) { size += chunk.length; if (size > E.LIMITS.jsonBytes) E.fail('RESOURCE', 'JSON stdin exceeds 2 MiB.'); chunks.push(chunk); }
  let request; try { request = JSON.parse(Buffer.concat(chunks).toString('utf8')); } catch { E.fail('INVALID', 'Provide one valid JSON object on stdin.'); }
  if (process.argv.length !== 3) E.fail('INVALID', 'Use node .claude/scripts/workflow-state.js <verb> and JSON stdin.');
  const result = execute(process.argv[2], request); process.stdout.write(JSON.stringify(result) + '\n');
}
if (require.main === module) main().catch(error => { process.stdout.write(JSON.stringify({ ok: false, code: error.code || 'IO', message: error.message, nextAction: error.nextAction || 'Inspect filesystem access and retain the existing workflow and evidence.' }) + '\n'); process.exitCode = 1; });
module.exports = { execute };
