// The declared column census for every table whose lifecycle field set is
// COMPUTED rather than listed.
//
// WHY THIS EXISTS. A `remaining_columns` field set means "the table's columns
// minus these", and `all_columns` means "the table's columns". Both are
// therefore complete BY CONSTRUCTION: `validateLifecycleClosure`'s "missing
// field" check could never fire for them, so an `ALTER TABLE ... ADD COLUMN`
// was silently absorbed into an existing governed set with no author decision
// and no build failure. C1 requires the opposite — "Build fails if a table,
// discovered row class, COLUMN, or governed JSON path is absent" — and 10a is
// the first slice to add columns under this gate.
//
// This is the LIST half of that guard (CLAUDE.md Respin rule 7). Adding a
// column to any table below is now a deliberate edit here, in the same change,
// after deciding which field set governs it.
//
// Generated once from the migrations, then maintained by hand. It is NOT
// re-derived at runtime: a census computed from the same source it validates
// would agree with itself and prove nothing.
export const LIFECYCLE_COLUMN_CENSUS: Readonly<Record<string, readonly string[]>> = {
  "account": ["access_token", "access_token_expires_at", "account_id", "created_at", "id", "id_token", "password", "provider_id", "refresh_token", "refresh_token_expires_at", "scope", "updated_at", "user_id"],
  "activation_cohort_daily": ["activated", "cohort_date", "excluded", "metric_version", "signups", "updated_at"],
  "auth_mail_outbox": ["action_expires_at", "admitted_at", "admitted_day_utc", "admitted_month_utc", "auth_user_id", "created_at", "delivery_attempt", "dispatched_at", "failure_code", "id", "operation_id", "provider_message_digest", "purpose", "recipient_digest", "reconciliation_digest", "resolved_at", "status", "updated_at"],
  "auto_topup_protocol_rollouts": ["activated_at", "authority_key_fingerprint", "authority_key_id", "drain_started_at", "fleet_quiesced_at", "protocol", "provider_reconciled_at", "reconciled_customers", "reconciled_payment_intents", "revision", "state", "stripe_account_id", "stripe_livemode", "updated_at"],
  "autopsies": ["analysis", "analysis_version", "content_digest", "created_at", "id", "matched_framework_id", "profile_id", "rights_basis", "rights_evidence_id", "rights_scope", "rights_subject_user_id", "status", "trend_item_id", "workspace_id"],
  "autopsy_cache_claims": ["active_system_attempt_id", "analysis_version", "attempt_count", "autopsy_id", "cache_scope_key", "content_digest", "created_at", "id", "last_failure_code", "lease_expires_at", "profile_id", "rights_basis", "rights_evidence_id", "rights_scope", "rights_subject_user_id", "status", "trend_item_id", "updated_at", "workspace_id"],
  "brain_activation_snapshots": ["created_at", "id", "killtest_doc_id", "performance_meta_doc_id", "profile_id", "strategy_doc_id", "voice_doc_id", "workspace_id"],
  "brain_docs": ["activated_at", "confirmed_at", "confirmed_by", "confirmed_content_sha256", "confirmed_fields", "content", "created_at", "evidence_counts", "id", "kind", "profile_id", "reason", "reference_corpus_ids", "source_evidence", "status", "superseded_at", "updated_at", "version", "workspace_id"],
  "config_versions": ["content", "created_at", "created_by", "version"],
  "creator_profiles": ["created_at", "display_name", "id", "lifecycle_version", "state", "updated_at", "workspace_id"],
  "credit_ledger": ["amount_cents", "auto_topup_attempt_id", "auto_topup_period_month_utc", "config_version", "created_at", "delta", "expires_at", "id", "kind", "pack_checkout_attempt_id", "reason_code", "ref_id", "ref_type", "stripe_event_id", "tier_checkout_attempt_id", "workspace_id"],
  "deletion_cancellation_proofs": ["auth_user_id", "consumed_at", "created_at", "expires_at", "factor_verified_at", "id", "operation_id", "recovery_session_id", "status_receipt_digest"],
  "deletion_external_commands": ["attempt", "created_at", "dispatched_at", "failure_code", "id", "kind", "operation_id", "payload_hash", "phase", "profile_id", "provider_ref_digest", "reconciliation_digest", "resolved_at", "scope", "status", "target_key", "updated_at", "user_id", "workspace_id"],
  "deletion_membership_snapshots": ["created_at", "id", "membership_id", "membership_version", "operation_id", "outcome", "outcome_at", "role", "user_id", "workspace_id"],
  "deletion_operation_transitions": ["created_at", "external_receipt_digest", "from_state", "id", "operation_id", "payload_hash", "profile_id", "requester_digest", "requester_user_id", "scope", "target_key", "to_state", "user_id", "version", "workspace_id"],
  "deletion_operations": ["acknowledged_at", "activation_applied_at", "activation_cohort_date", "activation_contribution_state", "activation_denominator", "activation_excluded", "activation_exclusion_source", "activation_membership_version", "activation_metric_version", "activation_numerator", "activation_payload_hash", "activation_receipt_digest", "blocked_resume_state", "cancellation_replay_digest", "created_at", "grace_expires_at", "heartbeat_at", "id", "idempotency_key", "identity_cancellation_receipt_expires_at", "journal_intent_base_version", "journal_intent_effective_at", "journal_intent_plan_digest", "journal_receipt_digest", "journal_version", "last_failure_code", "lease_expires_at", "lease_owner", "payload_hash", "profile_id", "profile_prior_state", "recovery_consumed_at", "recovery_delivered_at", "recovery_delivery_attempt", "recovery_delivery_attempted_at", "recovery_delivery_command_id", "recovery_delivery_receipt_digest", "recovery_delivery_recipient_digest", "recovery_delivery_reconciliation_digest", "recovery_delivery_status", "recovery_expires_at", "recovery_secret_digest", "recovery_secret_prefix", "request_membership_version", "request_profile_lifecycle_version", "request_session_digest", "request_workspace_lifecycle_version", "requested_at", "requester_digest", "requester_user_id", "retry_count", "scope", "state", "state_version", "target_key", "tombstoned_at", "updated_at", "user_id", "workspace_id"],
  "deletion_recovery_sessions": ["auth_user_id", "consumed_at", "created_at", "expires_at", "id", "operation_id", "rate_limit_key_digest", "secret_digest", "secret_prefix"],
  "first_billable_attempts": ["attempt_id", "created_at", "id", "profile_id", "purpose", "workspace_id"],
  "frameworks": ["applicability", "beats", "confidence", "created_at", "curated_by", "curator_status", "evidence_entries", "id", "name", "owner_profile_id", "retired_at", "rights_basis", "rights_evidence_id", "rights_subject_user_id", "saturation", "slug", "source_references", "superseded_at", "tested_caveats", "updated_at", "version", "visibility", "why_it_converts", "workspace_id"],
  "generation_attempts": ["attempt_id", "candidate", "claimed_at", "created_at", "debit_ledger_id", "generation_id", "id", "mode", "payload_sha256", "profile_id", "purpose", "refusal_code", "state", "terminal_at", "updated_at", "vendor_completed_at", "vendor_started_at", "workspace_id"],
  "generation_feedback": ["created_at", "generation_id", "id", "note", "profile_id", "reaction", "workspace_id"],
  "generations": ["attempt_id", "brain_activation_id", "config_version", "context_input_ids", "created_at", "framework_versions", "id", "kill_test", "mode", "model", "outcome", "output", "parent_id", "profile_id", "prompt_bundle_version", "refusal_reason", "request", "rewrite_count", "weakest_point", "workspace_id"],
  "membership_profile_selections": ["created_at", "id", "profile_id", "updated_at", "user_id", "workspace_id"],
  "memberships": ["created_at", "id", "lifecycle_state", "role", "suspended_role", "suspended_version", "suspension_operation_id", "updated_at", "user_id", "version", "workspace_id"],
  "model_usage": ["attempt_id", "config_version", "consumed_included_build", "cost_micro_usd", "cost_state", "created_at", "id", "model", "outcome", "profile_id", "prompt_bundle_version", "purpose", "resolved_tier", "stripe_price_id", "tokens_in", "tokens_out", "usage_raw", "workspace_id"],
  "onboarding_inputs": ["content", "content_sha256", "created_at", "field_key", "id", "input_class", "profile_id", "source_url", "workspace_id"],
  "onboarding_interview_drafts": ["answers", "created_at", "id", "profile_id", "submitted_at", "updated_at", "workspace_id"],
  "pause_periods": ["created_at", "ended_at", "ended_known_at", "id", "started_at", "started_known_at", "updated_at", "workspace_id"],
  "promotion_proposals": ["accepted_activation_id", "accepted_brain_doc_id", "basis_brain_doc_id", "created_at", "decision_at", "decision_role", "decision_user_id", "evidence_digest", "family_key", "id", "payload", "profile_id", "source", "status", "strength", "target_kind", "target_pointer", "updated_at", "workspace_id"],
  "proposal_evidence_feedback": ["feedback_id", "profile_id", "proposal_id", "workspace_id"],
  "proposal_evidence_results": ["profile_id", "proposal_id", "result_id", "role", "workspace_id"],
  "public_sample_spin_buckets": ["admitted", "blocked", "bucket_started_at", "duplicate", "expires_at", "id", "ip_hmac", "key_version", "refused", "updated_at"],
  "rate_limit": ["count", "id", "key", "last_request"],
  "results": ["audience_class", "confounders", "connector_event_id", "connector_observed_at", "connector_source", "conversion_denominator", "conversion_value", "created_at", "evidence_state", "generation_id", "id", "metric_declared_by_doc_id", "metric_key", "note", "observed_from", "observed_to", "platform", "profile_id", "reach_denominator", "reach_value", "treatment_key", "workspace_id"],
  "session": ["created_at", "expires_at", "id", "ip_address", "reauthenticated_at", "token", "updated_at", "user_agent", "user_id"],
  "stripe_events": ["id", "outcome", "payload", "processed_at", "receipt_attribution", "received_at", "stripe_customer_id", "tier_invoice_authority", "type", "workspace_id"],
  "stripe_finance_extracts": ["amount_excluding_tax_cents", "amount_including_tax_cents", "charge_id", "credit_note_id", "currency", "dispute_effective_at", "dispute_id", "dispute_status", "disputed_amount_cents", "extracted_at", "extraction_version", "id", "incomplete_reason", "ingested_at", "invoice_line_id", "object_id", "object_type", "payment_intent_id", "refund_id", "service_period_end", "service_period_start", "source_stripe_event_id", "status", "workspace_key"],
  "subscriptions": ["auto_topup_attempt_amount_cents", "auto_topup_attempt_claim_id", "auto_topup_attempt_claimed_at", "auto_topup_attempt_config_version", "auto_topup_attempt_credits", "auto_topup_attempt_currency", "auto_topup_attempt_customer_id", "auto_topup_attempt_cutover_at", "auto_topup_attempt_dispatched_at", "auto_topup_attempt_id", "auto_topup_attempt_idempotency_key", "auto_topup_attempt_ordinal", "auto_topup_attempt_payment_intent_id", "auto_topup_attempt_payment_intent_status", "auto_topup_attempt_period_month_utc", "auto_topup_attempt_price_id", "auto_topup_attempt_reserved_at", "auto_topup_attempt_validity_months", "auto_topup_enabled", "auto_topup_monthly_cap_cents", "auto_topup_protocol_version", "auto_topup_rearm_after_upgrade", "auto_topup_v1_enabled", "billing_contact_user_id", "cancel_at", "cancel_at_period_end", "created_at", "current_period_end", "current_period_start", "grace_expires_at", "id", "mirror_event_at", "paused_at", "resumes_at", "status", "stripe_customer_id", "stripe_price_id", "stripe_subscription_id", "tier_checkout_attempt_authority", "tier_checkout_attempt_customer_id", "tier_checkout_attempt_id", "tier_checkout_attempt_idempotency_key", "tier_checkout_attempt_price_id", "tier_checkout_attempt_reserved_at", "tier_checkout_attempt_session_id", "tier_checkout_attempt_stripe_account_id", "tier_checkout_attempt_stripe_livemode", "tier_checkout_attempt_subscription_generation", "tier_checkout_attempt_subscription_id", "tier_checkout_attempt_tier", "tier_checkout_fence_at", "tier_checkout_fence_observed_subscription_id", "tier_checkout_fence_status", "tier_checkout_fence_subscription_id", "tier_checkout_generation_attempt_id", "updated_at", "workspace_id"],
  "system_model_usage": ["business_date", "call_count", "cost_micro_usd", "cost_state", "created_at", "error_code", "id", "job_attempt_id", "job_id", "model", "outcome", "purpose", "reservation_overrun_micro_usd", "reserved_cost_micro_usd", "tokens_in", "tokens_out", "trend_item_id", "unknown_call_count"],
  "system_model_usage_reconciliations": ["actual_cost_micro_usd", "business_date", "created_at", "id", "job_attempt_id"],
  "system_spend_claims": ["autopsy_cache_claim_id", "business_date", "created_at", "id", "job_attempt_id", "job_id", "model", "purpose", "requested_micro_usd", "reserved_micro_usd", "status", "trend_item_id"],
  "system_spend_daily": ["business_date", "call_count", "cap_micro_usd", "created_at", "known_cost_micro_usd", "overrun_call_count", "overrun_micro_usd", "reserved_micro_usd", "unknown_call_count"],
  "system_worker_health": ["active_count", "budget_exhausted", "dead_letter_count", "last_heartbeat_at", "last_successful_run_at", "last_successful_schedule_at", "parked_count", "pool_capacity", "pool_in_use", "schedule_lag_seconds", "updated_at", "worker_name"],
  "tier_checkout_protocol_rollouts": ["activated_at", "drain_started_at", "fleet_quiesced_at", "protocol", "provider_reconciled_at", "reconciled_customers", "reconciled_sessions", "revision", "state", "stripe_account_id", "stripe_livemode", "updated_at"],
  "tracked_niches": ["created_at", "id", "niche", "profile_id", "workspace_id"],
  "trend_items": ["baseline_observation_ids", "baseline_sample_size", "baseline_state", "baseline_window_ends_at", "baseline_window_starts_at", "channel_id", "channel_median_recent_views", "created_at", "external_video_id", "id", "niche", "outlier_ratio", "profile_id", "rights_scope", "saturation", "saturation_matching_items", "saturation_method_version", "saturation_population_size", "saturation_prevalence", "saturation_unmeasured_reason", "saturation_window_ends_at", "saturation_window_starts_at", "source_id", "source_published_at", "stale_at", "title", "transcript_state", "updated_at", "video_views", "workspace_id"],
  "trend_sources": ["created_at", "external_id", "id", "kind", "profile_id", "source_url", "workspace_id"],
  "trend_transcripts": ["content", "content_digest", "created_at", "id", "profile_id", "provenance", "reference_input_id", "rights_basis", "rights_evidence_id", "rights_scope", "rights_subject_user_id", "trend_item_id", "workspace_id"],
  "user": ["created_at", "email", "email_verified", "id", "image", "name", "ordinary_login_disabled_at", "updated_at"],
  "users": ["auth_user_id", "created_at", "id", "lifecycle_state", "updated_at"],
  "verification": ["created_at", "expires_at", "id", "identifier", "updated_at", "value"],
  "workspace_spend_monthly": ["call_count", "cost_micro_usd", "created_at", "id", "period_month", "tier", "unknown_call_count", "updated_at", "workspace_id"],
  "workspaces": ["created_at", "id", "lifecycle_state", "lifecycle_version", "name", "updated_at"],
};
