ALTER TABLE "deletion_operation_transitions" DROP CONSTRAINT "deletion_operation_transitions_target_shape";--> statement-breakpoint
ALTER TABLE "deletion_operations" ADD COLUMN "request_membership_version" integer;--> statement-breakpoint
ALTER TABLE "deletion_operations" ADD COLUMN "request_workspace_lifecycle_version" integer;--> statement-breakpoint
ALTER TABLE "deletion_operations" ADD COLUMN "request_profile_lifecycle_version" integer;--> statement-breakpoint
ALTER TABLE "deletion_operations" ADD COLUMN "journal_intent_base_version" integer;--> statement-breakpoint
ALTER TABLE "deletion_operations" ADD COLUMN "journal_intent_plan_digest" text;--> statement-breakpoint
ALTER TABLE "deletion_operations" ADD COLUMN "journal_intent_effective_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "deletion_operation_transitions" ADD CONSTRAINT "deletion_operation_transitions_target_shape" CHECK (("deletion_operation_transitions"."scope" = 'identity' AND "deletion_operation_transitions"."user_id" IS NOT NULL AND "deletion_operation_transitions"."workspace_id" IS NULL AND "deletion_operation_transitions"."profile_id" IS NULL AND "deletion_operation_transitions"."target_key" = 'identity:' || "deletion_operation_transitions"."user_id"::text)
          OR ("deletion_operation_transitions"."scope" = 'profile' AND "deletion_operation_transitions"."user_id" IS NULL AND "deletion_operation_transitions"."workspace_id" IS NOT NULL AND "deletion_operation_transitions"."profile_id" IS NOT NULL AND "deletion_operation_transitions"."target_key" = 'profile:' || "deletion_operation_transitions"."workspace_id"::text || ':' || "deletion_operation_transitions"."profile_id"::text)
          OR ("deletion_operation_transitions"."scope" = 'workspace' AND "deletion_operation_transitions"."user_id" IS NULL AND "deletion_operation_transitions"."workspace_id" IS NOT NULL AND "deletion_operation_transitions"."profile_id" IS NULL AND "deletion_operation_transitions"."target_key" = 'workspace:' || "deletion_operation_transitions"."workspace_id"::text));--> statement-breakpoint
ALTER TABLE "deletion_operations" ADD CONSTRAINT "deletion_operations_journal_intent_shape" CHECK (("deletion_operations"."journal_intent_base_version" IS NULL AND "deletion_operations"."journal_intent_plan_digest" IS NULL AND "deletion_operations"."journal_intent_effective_at" IS NULL)
          OR ("deletion_operations"."journal_intent_base_version" >= 0 AND "deletion_operations"."journal_intent_plan_digest" ~ '^[0-9a-f]{64}$' AND "deletion_operations"."journal_intent_effective_at" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "deletion_operations" ADD CONSTRAINT "deletion_operations_request_authority_epoch_shape" CHECK (("deletion_operations"."scope" = 'identity' AND "deletion_operations"."request_membership_version" IS NULL AND "deletion_operations"."request_workspace_lifecycle_version" IS NULL AND "deletion_operations"."request_profile_lifecycle_version" IS NULL)
          OR ("deletion_operations"."scope" = 'workspace' AND "deletion_operations"."request_membership_version" >= 1 AND "deletion_operations"."request_workspace_lifecycle_version" >= 1 AND "deletion_operations"."request_profile_lifecycle_version" IS NULL)
          OR ("deletion_operations"."scope" = 'profile' AND "deletion_operations"."request_membership_version" >= 1 AND "deletion_operations"."request_workspace_lifecycle_version" >= 1 AND "deletion_operations"."request_profile_lifecycle_version" >= 1));