CREATE TYPE "public"."system_spend_purpose" AS ENUM('trend_autopsy', 'public_sample_spin');--> statement-breakpoint
ALTER TABLE "system_model_usage" DROP CONSTRAINT "system_model_usage_call_shape";--> statement-breakpoint
ALTER TABLE "system_model_usage" DROP CONSTRAINT "system_model_usage_attribution_shape";--> statement-breakpoint
ALTER TABLE "system_spend_claims" DROP CONSTRAINT "system_spend_claims_attribution_shape";--> statement-breakpoint
ALTER TABLE "system_model_usage" ALTER COLUMN "trend_item_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "system_model_usage" ALTER COLUMN "purpose" SET DATA TYPE "public"."system_spend_purpose" USING "purpose"::"public"."system_spend_purpose";--> statement-breakpoint
ALTER TABLE "system_spend_claims" ALTER COLUMN "trend_item_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "system_spend_claims" ALTER COLUMN "autopsy_cache_claim_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "system_spend_claims" ALTER COLUMN "purpose" SET DATA TYPE "public"."system_spend_purpose" USING "purpose"::"public"."system_spend_purpose";--> statement-breakpoint
ALTER TABLE "system_model_usage" ADD CONSTRAINT "system_model_usage_call_shape" CHECK ("system_model_usage"."call_count" BETWEEN 0 AND 4 AND "system_model_usage"."unknown_call_count" BETWEEN 0 AND "system_model_usage"."call_count" AND (("system_model_usage"."outcome" = 'budget_exhausted') = ("system_model_usage"."call_count" = 0)) AND ("system_model_usage"."purpose" <> 'public_sample_spin' OR "system_model_usage"."call_count" <= 3) AND ("system_model_usage"."outcome" <> 'succeeded' OR ("system_model_usage"."cost_state" = 'measured' AND (("system_model_usage"."purpose" = 'trend_autopsy' AND "system_model_usage"."call_count" = 4) OR ("system_model_usage"."purpose" = 'public_sample_spin' AND "system_model_usage"."call_count" BETWEEN 2 AND 3)))) AND (("system_model_usage"."cost_state" = 'unknown') = ("system_model_usage"."unknown_call_count" > 0)));--> statement-breakpoint
ALTER TABLE "system_model_usage" ADD CONSTRAINT "system_model_usage_attribution_shape" CHECK ("system_model_usage"."job_attempt_id" ~ '[^[:space:]]' AND "system_model_usage"."job_id" ~ '[^[:space:]]' AND "system_model_usage"."model" ~ '[^[:space:]]' AND (("system_model_usage"."purpose" = 'trend_autopsy' AND "system_model_usage"."trend_item_id" IS NOT NULL) OR ("system_model_usage"."purpose" = 'public_sample_spin' AND "system_model_usage"."trend_item_id" IS NULL)));--> statement-breakpoint
ALTER TABLE "system_spend_claims" ADD CONSTRAINT "system_spend_claims_attribution_shape" CHECK ("system_spend_claims"."job_attempt_id" ~ '[^[:space:]]' AND "system_spend_claims"."job_id" ~ '[^[:space:]]' AND "system_spend_claims"."model" ~ '[^[:space:]]' AND (("system_spend_claims"."purpose" = 'trend_autopsy' AND "system_spend_claims"."trend_item_id" IS NOT NULL AND "system_spend_claims"."autopsy_cache_claim_id" IS NOT NULL) OR ("system_spend_claims"."purpose" = 'public_sample_spin' AND "system_spend_claims"."trend_item_id" IS NULL AND "system_spend_claims"."autopsy_cache_claim_id" IS NULL)));