[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$failures = New-Object System.Collections.Generic.List[string]
$passes = New-Object System.Collections.Generic.List[string]

function Invoke-Diagnostic {
    param(
        [Parameter(Mandatory)][string]$Label,
        [Parameter(Mandatory)][scriptblock]$Action
    )
    try {
        & $Action
        $script:passes.Add($Label)
    } catch {
        $script:failures.Add("$Label`: $($_.Exception.Message)")
    }
}

Push-Location $projectRoot
try {
    Invoke-Diagnostic 'shared JSON policy files parse' {
        Get-Content -LiteralPath '.claude\guardrails.rules.json' -Raw | ConvertFrom-Json | Out-Null
        Get-Content -LiteralPath '.claude\workspaces.json' -Raw | ConvertFrom-Json | Out-Null
        Get-Content -LiteralPath '.codex\hooks.json' -Raw | ConvertFrom-Json | Out-Null
    }
    Invoke-Diagnostic 'required project instruction files exist' {
        foreach ($file in @('AGENTS.md', 'CLAUDE.md', '.codebase-map\SUMMARY.md')) {
            if (-not (Test-Path -LiteralPath $file)) { throw "Missing $file" }
        }
    }
    Invoke-Diagnostic 'Codex hook self-tests pass' {
        & node '.codex\hooks\guardrails.js' --self-test | Out-Null
        if ($LASTEXITCODE -ne 0) { throw 'guardrails self-test failed' }
        & node '.codex\hooks\post-edit-check.js' --self-test | Out-Null
        if ($LASTEXITCODE -ne 0) { throw 'post-edit self-test failed' }
    }
    Invoke-Diagnostic 'Codex CLI accepts the project configuration' {
        & codex features list | Out-Null
        if ($LASTEXITCODE -ne 0) { throw 'Codex rejected .codex/config.toml' }
    }
    Invoke-Diagnostic 'Codex command policy blocks destructive Git reset' {
        $policy = & codex execpolicy check --rules '.codex\rules\safety.rules' -- git reset --hard HEAD |
            ConvertFrom-Json
        if ($LASTEXITCODE -ne 0 -or $policy.decision -ne 'forbidden') {
            throw 'Expected forbidden decision for git reset --hard'
        }
    }
    Invoke-Diagnostic 'Claude/Codex discovery adapters are synchronized' {
        & powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File '.codex\scripts\sync-claude-compat.ps1' -Check | Out-Null
        if ($LASTEXITCODE -ne 0) { throw 'adapter synchronization check failed' }
    }
    Invoke-Diagnostic 'all generated skill wrappers have minimal frontmatter' {
        Get-ChildItem -LiteralPath '.agents\skills' -Filter 'SKILL.md' -Recurse | ForEach-Object {
            $text = [System.IO.File]::ReadAllText($_.FullName)
            if ($text.Contains('Generated by .codex/scripts/sync-claude-compat.ps1')) {
                $match = [regex]::Match($text, '(?s)\A---\s*\n(.*?)\n---')
                if (-not $match.Success) { throw "Invalid frontmatter: $($_.FullName)" }
                $keys = [regex]::Matches($match.Groups[1].Value, '(?m)^([A-Za-z0-9_-]+):') |
                    ForEach-Object { $_.Groups[1].Value }
                if (($keys | Sort-Object) -join ',' -ne 'description,name') {
                    throw "Unexpected frontmatter keys in $($_.FullName): $($keys -join ', ')"
                }
            }
        }
    }
    Invoke-Diagnostic 'generated agent count matches Claude roles' {
        $sourceCount = (Get-ChildItem -LiteralPath '.claude\agents' -File -Filter '*.md' |
            Where-Object Name -ne '_critic-template.md').Count
        $targetCount = (Get-ChildItem -LiteralPath '.codex\agents' -File -Filter '*.toml').Count
        if ($sourceCount -ne $targetCount) { throw "source=$sourceCount target=$targetCount" }
    }
} finally {
    Pop-Location
}

$passes | ForEach-Object { Write-Host "PASS  $_" }
if ($failures.Count -gt 0) {
    $failures | ForEach-Object { Write-Host "FAIL  $_" -ForegroundColor Red }
    exit 1
}
Write-Host "Codex workflow doctor passed ($($passes.Count) checks)."
