[CmdletBinding()]
param([switch]$Deep)

$ErrorActionPreference = 'Stop'
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$failures = New-Object System.Collections.Generic.List[string]
$passes = New-Object System.Collections.Generic.List[string]
$generatedAgentMarker = '# Generated by .codex/scripts/sync-claude-compat.ps1; do not edit.'

function Invoke-Diagnostic {
    param(
        [Parameter(Mandatory)][string]$Label,
        [Parameter(Mandatory)][scriptblock]$Action
    )
    try {
        & $Action
        $script:passes.Add($Label)
    } catch {
        $script:failures.Add("$Label`: $($_.Exception.Message)")
    }
}

function Get-ClaudeTreeDigest {
    $builder = New-Object System.Text.StringBuilder
    Get-ChildItem -LiteralPath '.claude' -File -Recurse | Sort-Object FullName | ForEach-Object {
        $relative = $_.FullName.Substring($projectRoot.Length + 1).Replace('\', '/')
        $hash = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash
        [void]$builder.Append($relative).Append("`0").Append($hash).Append("`n")
    }
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($builder.ToString())
        return -join ($sha.ComputeHash($bytes) | ForEach-Object { $_.ToString('x2') })
    } finally {
        $sha.Dispose()
    }
}

function Assert-ContainsLiteral {
    param([string]$Text, [string]$Expected, [string]$Label)
    if (-not $Text.Contains($Expected)) { throw "Missing $Label ($Expected)" }
}

Push-Location $projectRoot
try {
    Invoke-Diagnostic 'policy and hook JSON files parse' {
        Get-Content -LiteralPath '.claude\guardrails.rules.json' -Raw | ConvertFrom-Json | Out-Null
        foreach ($file in @('.codex\codex.rules.json', '.codex\workspaces.json', '.codex\hooks.json')) {
            Get-Content -LiteralPath $file -Raw | ConvertFrom-Json | Out-Null
        }
    }
    Invoke-Diagnostic 'required project instruction and Codex overlay files exist' {
        foreach ($file in @('AGENTS.md', 'CLAUDE.md', '.codebase-map\SUMMARY.md', '.codex\codex-overlay.md')) {
            if (-not (Test-Path -LiteralPath $file)) { throw "Missing $file" }
        }
    }
    Invoke-Diagnostic 'Codex hook self-tests pass' {
        & node '.codex\hooks\guardrails.js' --self-test | Out-Null
        if ($LASTEXITCODE -ne 0) { throw 'guardrails self-test failed' }
        & node '.codex\hooks\post-edit-check.js' --self-test | Out-Null
        if ($LASTEXITCODE -ne 0) { throw 'post-edit self-test failed' }
    }
    Invoke-Diagnostic 'Codex routing configuration is exact' {
        $config = Get-Content -LiteralPath '.codex\config.toml' -Raw
        foreach ($pair in @(
            @('model = "gpt-5.6-sol"', 'Sol orchestrator'),
            @('model_reasoning_effort = "xhigh"', 'orchestrator effort'),
            @('hooks = true', 'hook feature'),
            @('default_subagent_model = "gpt-5.6-terra"', 'default subagent'),
            @('default_subagent_reasoning_effort = "medium"', 'default subagent effort'),
            @('max_concurrent_threads_per_session = 4', 'thread ceiling')
        )) { Assert-ContainsLiteral -Text $config -Expected $pair[0] -Label $pair[1] }
    }
    Invoke-Diagnostic 'Codex hooks are restored and point only to Codex hook scripts' {
        $hooks = Get-Content -LiteralPath '.codex\hooks.json' -Raw | ConvertFrom-Json
        foreach ($event in @('SessionStart', 'PreToolUse', 'PostToolUse')) {
            if (-not $hooks.hooks.$event -or $hooks.hooks.$event.Count -lt 1) { throw "Missing $event hook" }
        }
        $text = Get-Content -LiteralPath '.codex\hooks.json' -Raw
        if ($text.Contains('.claude')) { throw 'Codex hook map must not execute Claude hook files' }
    }
    Invoke-Diagnostic 'Codex command policy still blocks destructive Git reset' {
        $text = Get-Content -LiteralPath '.codex\rules\safety.rules' -Raw
        if ($text -notmatch 'git.*reset' -or $text -notmatch 'decision\s*=\s*"forbidden"') {
            throw 'Expected a forbidden git reset rule in .codex/rules/safety.rules'
        }
    }
    Invoke-Diagnostic 'Claude/Codex discovery adapters are synchronized without Claude writes' {
        $before = Get-ClaudeTreeDigest
        & powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File '.codex\scripts\sync-claude-compat.ps1' -Check | Out-Null
        if ($LASTEXITCODE -ne 0) { throw 'adapter synchronization check failed' }
        $after = Get-ClaudeTreeDigest
        if ($before -ne $after) { throw 'Claude workflow tree changed during adapter check' }
    }
    Invoke-Diagnostic 'generated adapter target allowlist is present' {
        $text = Get-Content -LiteralPath '.codex\scripts\sync-claude-compat.ps1' -Raw
        foreach ($literal in @("'.agents\skills'", "'.codex\agents'", 'Assert-GeneratedTarget')) {
            Assert-ContainsLiteral -Text $text -Expected $literal -Label 'generator target allowlist'
        }
    }
    Invoke-Diagnostic 'all generated skill wrappers have minimal frontmatter' {
        Get-ChildItem -LiteralPath '.agents\skills' -Filter 'SKILL.md' -Recurse | ForEach-Object {
            $text = [System.IO.File]::ReadAllText($_.FullName)
            if ($text.Contains('Generated by .codex/scripts/sync-claude-compat.ps1')) {
                $match = [regex]::Match($text, '(?s)\A---\s*\n(.*?)\n---')
                if (-not $match.Success) { throw "Invalid frontmatter: $($_.FullName)" }
                $keys = [regex]::Matches($match.Groups[1].Value, '(?m)^([A-Za-z0-9_-]+):') |
                    ForEach-Object { $_.Groups[1].Value }
                if (($keys | Sort-Object) -join ',' -ne 'description,name') {
                    throw "Unexpected frontmatter keys in $($_.FullName): $($keys -join ', ')"
                }
            }
        }
    }
    Invoke-Diagnostic 'generated agent count and model routes match Claude roles' {
        $sourceCount = (Get-ChildItem -LiteralPath '.claude\agents' -File -Filter '*.md' |
            Where-Object Name -ne '_critic-template.md').Count
        $generated = @(Get-ChildItem -LiteralPath '.codex\agents' -File -Filter '*.toml' | Where-Object {
            [System.IO.File]::ReadAllText($_.FullName).Contains($generatedAgentMarker)
        })
        if ($sourceCount -ne $generated.Count) { throw "source=$sourceCount generated=$($generated.Count)" }
        foreach ($file in $generated) {
            $text = [System.IO.File]::ReadAllText($file.FullName)
            if ($text.Contains('sandbox_mode = "read-only"')) {
                Assert-ContainsLiteral -Text $text -Expected 'model = "gpt-5.6-sol"' -Label "$($file.Name) review model"
                Assert-ContainsLiteral -Text $text -Expected 'model_reasoning_effort = "max"' -Label "$($file.Name) review effort"
            } else {
                Assert-ContainsLiteral -Text $text -Expected 'model = "gpt-5.6-terra"' -Label "$($file.Name) worker model"
                Assert-ContainsLiteral -Text $text -Expected 'model_reasoning_effort = "high"' -Label "$($file.Name) worker effort"
            }
        }
    }
    Invoke-Diagnostic 'native economy agents have exact routes' {
        $expected = @{
            'economy-explorer.toml' = @('model = "gpt-5.6-terra"', 'model_reasoning_effort = "medium"', 'sandbox_mode = "read-only"')
            'verification-runner.toml' = @('model = "gpt-5.6-luna"', 'model_reasoning_effort = "low"')
            'lean-gate-reviewer.toml' = @('model = "gpt-5.6-sol"', 'model_reasoning_effort = "max"', 'sandbox_mode = "read-only"')
        }
        foreach ($name in $expected.Keys) {
            $path = Join-Path '.codex\agents' $name
            if (-not (Test-Path -LiteralPath $path)) { throw "Missing native agent $name" }
            $text = Get-Content -LiteralPath $path -Raw
            foreach ($literal in $expected[$name]) { Assert-ContainsLiteral -Text $text -Expected $literal -Label $name }
        }
    }
    Invoke-Diagnostic 'post-edit checks use the Codex-owned workspace map' {
        $text = Get-Content -LiteralPath '.codex\hooks\post-edit-check.js' -Raw
        Assert-ContainsLiteral -Text $text -Expected 'path.join(projectRoot, ".codex", "workspaces.json")' -Label 'Codex workspace map'
        if ($text.Contains('path.join(projectRoot, ".claude", "workspaces.json")')) {
            throw 'post-edit checks still execute the Claude workspace map'
        }
    }
    if ($Deep) {
        Invoke-Diagnostic 'Codex CLI accepts the project configuration' {
            & codex features list | Out-Null
            if ($LASTEXITCODE -ne 0) { throw 'Codex rejected project configuration' }
        }
        Invoke-Diagnostic 'Codex execpolicy evaluates destructive Git reset as forbidden' {
            $policy = & codex execpolicy check --rules '.codex\rules\safety.rules' -- git reset --hard HEAD | ConvertFrom-Json
            if ($LASTEXITCODE -ne 0 -or $policy.decision -ne 'forbidden') { throw 'Expected forbidden decision' }
        }
    }
} finally {
    Pop-Location
}

$passes | ForEach-Object { Write-Host "PASS  $_" }
if ($failures.Count -gt 0) {
    $failures | ForEach-Object { Write-Host "FAIL  $_" -ForegroundColor Red }
    exit 1
}
Write-Host "Codex workflow doctor passed ($($passes.Count) checks)."
