[CmdletBinding()]
param([switch]$Check)

$ErrorActionPreference = 'Stop'
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$skillMarker = '<!-- Generated by .codex/scripts/sync-claude-compat.ps1; do not edit. -->'
$agentMarker = '# Generated by .codex/scripts/sync-claude-compat.ps1; do not edit.'
$issues = New-Object System.Collections.Generic.List[string]
$created = 0
$updated = 0
$covered = 0

function Read-FrontMatter {
    param([Parameter(Mandatory)][string]$Path)
    $lines = [System.IO.File]::ReadAllLines($Path)
    $result = @{}
    if ($lines.Count -lt 3 -or $lines[0].Trim() -ne '---') { return $result }
    for ($index = 1; $index -lt $lines.Count; $index++) {
        if ($lines[$index].Trim() -eq '---') { break }
        if ($lines[$index] -match '^([A-Za-z0-9_-]+):\s*(.*)$') {
            $value = $Matches[2].Trim()
            if (($value.StartsWith('"') -and $value.EndsWith('"')) -or
                ($value.StartsWith("'") -and $value.EndsWith("'"))) {
                $value = $value.Substring(1, $value.Length - 2)
            }
            $result[$Matches[1]] = $value
        }
    }
    return $result
}

function Get-CompactDescription {
    param([string]$Description, [string]$Fallback, [int]$MaximumLength = 360)
    $value = if ([string]::IsNullOrWhiteSpace($Description)) { $Fallback } else { $Description }
    $value = [regex]::Replace($value, '\s+', ' ').Trim()
    if ($value.Length -gt $MaximumLength) {
        $value = $value.Substring(0, $MaximumLength - 3).TrimEnd() + '...'
    }
    return $value
}

function Write-GeneratedFile {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Content,
        [Parameter(Mandatory)][string]$Marker,
        [switch]$AllowExistingImplementation
    )
    $parent = Split-Path -Parent $Path
    if (Test-Path -LiteralPath $Path) {
        $current = [System.IO.File]::ReadAllText($Path)
        if (-not $current.Contains($Marker)) {
            if ($AllowExistingImplementation) { $script:covered++; return }
            $script:issues.Add("Refusing to overwrite non-generated file: $Path")
            return
        }
        if ($current.Replace("`r`n", "`n") -eq $Content.Replace("`r`n", "`n")) {
            $script:covered++
            return
        }
        if ($Check) { $script:issues.Add("Generated adapter is stale: $Path"); return }
        [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
        $script:updated++
        return
    }
    if ($Check) { $script:issues.Add("Missing generated adapter: $Path"); return }
    [System.IO.Directory]::CreateDirectory($parent) | Out-Null
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
    $script:created++
}

function New-SkillWrapper {
    param(
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][string]$Description,
        [Parameter(Mandatory)][string]$Source,
        [switch]$IsCommand
    )
    $invocation = '$' + $Name
    $fallback = if ($IsCommand) {
        "Run the migrated Claude /$Name workflow in Codex. Use when the user invokes $invocation."
    } else {
        "Use the canonical project skill $Name from the shared Claude workflow pack."
    }
    $descriptionText = if ($IsCommand) {
        Get-CompactDescription -Description "Use $invocation for the migrated Claude /$Name workflow. $Description" -Fallback $fallback
    } else {
        Get-CompactDescription -Description $Description -Fallback $fallback
    }

    $body = New-Object System.Collections.Generic.List[string]
    $body.Add('---'); $body.Add("name: $Name"); $body.Add('description: >-')
    $body.Add("  $descriptionText"); $body.Add('---'); $body.Add('')
    $body.Add("# $Name"); $body.Add(''); $body.Add($skillMarker); $body.Add('')
    $body.Add("Read ``$Source`` completely before acting. Treat its instructions and frontmatter constraints as the authoritative workflow; this file only exposes it to Codex discovery.")
    $body.Add('')
    $body.Add('Honor any `allowed-tools` metadata as a behavioral allowlist even when Codex cannot enforce that metadata declaratively.')
    $body.Add('')
    $body.Add('Apply the Claude-to-Codex compatibility mappings in the repository root `AGENTS.md`. Resolve every relative resource or script from the canonical source directory.')
    if ($IsCommand) {
        $body.Add('')
        $body.Add('If the workflow modifies Claude skills, commands, or agents, finish by running `.codex/scripts/sync-claude-compat.ps1` so Codex discovery remains current.')
    }
    if ($Name -eq 'doctor') {
        $body.Add('')
        $body.Add('For Codex parity, also run `.codex/scripts/doctor.ps1`; report both shared-pack and Codex-adapter failures truthfully.')
    }
    $body.Add('')
    $target = Join-Path $projectRoot ".agents\skills\$Name\SKILL.md"
    Write-GeneratedFile -Path $target -Content ($body -join "`n") -Marker $skillMarker -AllowExistingImplementation
}

Get-ChildItem -LiteralPath (Join-Path $projectRoot '.claude\skills') -Directory | Sort-Object Name | ForEach-Object {
    $sourceFile = Join-Path $_.FullName 'SKILL.md'
    if (Test-Path -LiteralPath $sourceFile) {
        $metadata = Read-FrontMatter -Path $sourceFile
        $name = if ($metadata.name) { $metadata.name } else { $_.Name }
        New-SkillWrapper -Name $name -Description $metadata.description -Source ".claude/skills/$($_.Name)/SKILL.md"
    }
}

$claudeCommands = Join-Path $projectRoot '.claude\commands'
Get-ChildItem -LiteralPath $claudeCommands -File -Filter '*.md' | Sort-Object Name | ForEach-Object {
    $metadata = Read-FrontMatter -Path $_.FullName
    $name = [System.IO.Path]::GetFileNameWithoutExtension($_.Name)
    New-SkillWrapper -Name $name -Description $metadata.description -Source ".claude/commands/$($_.Name)" -IsCommand
}
$watchSource = Join-Path $claudeCommands 'watch\SKILL.md'
if (Test-Path -LiteralPath $watchSource) {
    $metadata = Read-FrontMatter -Path $watchSource
    New-SkillWrapper -Name 'watch' -Description $metadata.description -Source '.claude/commands/watch/SKILL.md' -IsCommand
}

Get-ChildItem -LiteralPath (Join-Path $projectRoot '.claude\agents') -File -Filter '*.md' |
    Where-Object Name -ne '_critic-template.md' | Sort-Object Name | ForEach-Object {
    $metadata = Read-FrontMatter -Path $_.FullName
    $name = if ($metadata.name) { $metadata.name } else { [System.IO.Path]::GetFileNameWithoutExtension($_.Name) }
    $description = Get-CompactDescription -Description $metadata.description -Fallback "Project agent role $name from the shared Claude workflow pack."
    $effort = if ($metadata.effort -in @('high', 'max')) { $metadata.effort } else { 'high' }
    $readOnly = $metadata.tools -notmatch '(^|,\s*)(Write|Edit|MultiEdit)(,|$)'
    $source = ".claude/agents/$($_.Name)"
    $tomlName = $name | ConvertTo-Json -Compress
    $tomlDescription = $description | ConvertTo-Json -Compress

    $content = New-Object System.Collections.Generic.List[string]
    $content.Add($agentMarker); $content.Add("name = $tomlName")
    $content.Add("description = $tomlDescription")
    $content.Add("model_reasoning_effort = `"$effort`"")
    if ($readOnly) { $content.Add('sandbox_mode = "read-only"') }
    $content.Add('developer_instructions = """')
    $content.Add("First action: read ``$source`` completely and follow its body as the authoritative role instructions.")
    $content.Add('Translate Claude-specific primitives using the repository root `AGENTS.md`. Preserve the original role boundaries and evidence standards.')
    $content.Add('Honor the source `tools` metadata as a behavioral allowlist; do not use a broader Codex capability merely because it is available.')
    if ($readOnly) { $content.Add('This is a read-only review role: inspect and report, but do not edit files or perform state-changing commands.') }
    $content.Add('"""'); $content.Add('')
    $target = Join-Path $projectRoot ".codex\agents\$name.toml"
    Write-GeneratedFile -Path $target -Content ($content -join "`n") -Marker $agentMarker
}

if ($issues.Count -gt 0) {
    $issues | ForEach-Object { Write-Error $_ }
    exit 1
}
Write-Host "Claude/Codex adapters current: created=$created updated=$updated existing=$covered"
